<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Keuntungan Klub Generasi Maju</name>
   <tag></tag>
   <elementGuidId>d0c2bc20-e673-4c5e-b7ea-622232876f09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='keuntungan-kbs-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#keuntungan-kbs-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ef54cf4a-5c3c-444e-ab8c-65fa4d69b390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link keuntungan-kbs active</value>
      <webElementGuid>df2e9c93-6840-441f-9991-83cbbf7f8147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keuntungan-kbs-tab</value>
      <webElementGuid>9c385f07-f674-4165-ad59-d39d4548d3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4f3adb52-5347-4b19-a5a8-601b8053c329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#keuntungan-kbs</value>
      <webElementGuid>3c597e79-f6d5-468f-88b1-ccfaca2ed129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>2250beae-37ad-4acb-add8-45eb022826f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>keuntungan-kbs</value>
      <webElementGuid>1f4814cf-47a0-4256-a385-829fc34c62b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dec1fde4-77b6-4fb4-a51f-630048c0ab37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Keuntungan Klub Generasi Maju </value>
      <webElementGuid>f7a8151a-0b4e-4c89-ba3e-41ed95ffb1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keuntungan-kbs-tab&quot;)</value>
      <webElementGuid>cc027666-b929-44c3-9941-04c76ac33abf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='keuntungan-kbs-tab']</value>
      <webElementGuid>dc8ee317-bb32-44bc-abf5-d685a5d27925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li/a</value>
      <webElementGuid>f881a6dd-817d-4ac7-a76d-dfa17ef33975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Keuntungan Klub Generasi Maju')]</value>
      <webElementGuid>cadc22da-2aba-4cb3-89c6-7688545b98d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bergabunglah di Klub Generasi Maju!'])[1]/following::a[1]</value>
      <webElementGuid>9b52f45e-087e-41c0-9db9-78b8c5367e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekomendasi Takaran Susu SGM untuk Anak'])[1]/following::a[1]</value>
      <webElementGuid>d6e88687-3262-4275-bbca-4c1a37959308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEKANISME KLUB GENERASI MAJU'])[1]/preceding::a[1]</value>
      <webElementGuid>14bfe820-76fd-4008-bcef-c11422649b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGM Eksplor 1+'])[2]/preceding::a[2]</value>
      <webElementGuid>4306d12e-6e0a-4f32-9534-6ca65c6aa255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keuntungan Klub Generasi Maju']/parent::*</value>
      <webElementGuid>1f35f75e-bd16-4db7-bccd-08c0136115cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#keuntungan-kbs')]</value>
      <webElementGuid>84e703e5-aa0f-4c9d-9144-bf1814aa20bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[7]/div/div/ul/li/a</value>
      <webElementGuid>e599d3d6-4b96-4083-b698-0fc954f8921c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'keuntungan-kbs-tab' and @href = '#keuntungan-kbs' and (text() = '
Keuntungan Klub Generasi Maju ' or . = '
Keuntungan Klub Generasi Maju ')]</value>
      <webElementGuid>d51964ee-b815-4075-8456-9d6b97abdd2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
