<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KEUNTUNGAN KLUB GENERASI MAJU</name>
   <tag></tag>
   <elementGuidId>384534a2-d18d-4662-b786-72cf7a8f76ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keuntungan-kbs-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='keuntungan-kbs-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dd438fd9-64e4-4433-a4d7-2511c0046292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link keuntungan-kbs active</value>
      <webElementGuid>29183386-3e6a-4f39-b07d-47676f7cd0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keuntungan-kbs-tab</value>
      <webElementGuid>404ee38a-e889-49ee-b76d-8ef8ee928919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>320a1560-546b-4a83-b44d-6daef8b872aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#keuntungan-kbs</value>
      <webElementGuid>fa668127-5724-4420-84d7-bfd2d0c0917b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>bc3cee57-ec30-4353-a25c-0239b4e26868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>keuntungan-kbs</value>
      <webElementGuid>f42b8cfc-d33f-43c5-8a49-9dcac15fa814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7ffe1e63-04cc-464e-b9a4-693e97f6399d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
KEUNTUNGAN KLUB GENERASI MAJU </value>
      <webElementGuid>a51748db-1dab-45a2-acf1-57ed3d1e93ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keuntungan-kbs-tab&quot;)</value>
      <webElementGuid>ca2cdca5-8513-44ce-9068-2f483f02cbc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='keuntungan-kbs-tab']</value>
      <webElementGuid>bbb673fe-d375-4b9c-a956-193899d465f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li/a</value>
      <webElementGuid>cd6a3c9c-7208-4be0-aba2-b76ca363e931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'KEUNTUNGAN KLUB GENERASI MAJU')]</value>
      <webElementGuid>c8a72381-fdd6-47af-a020-6bed62345588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bergabunglah di Klub Generasi Maju!'])[1]/following::a[1]</value>
      <webElementGuid>eda80451-128e-4749-ae68-97e5e42ee052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGM Soya'])[1]/following::a[2]</value>
      <webElementGuid>8d3f44ab-d28b-4dd7-9bbb-01bb7cd1d365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEKANISME KLUB GENERASI MAJU'])[1]/preceding::a[1]</value>
      <webElementGuid>9e0d3335-f120-4b3e-be4a-e5f097da75e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dapatkan Poin Ekstra'])[1]/preceding::a[2]</value>
      <webElementGuid>817218ce-c824-4e16-9778-1bc52a74105e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KEUNTUNGAN KLUB GENERASI MAJU']/parent::*</value>
      <webElementGuid>865285c6-7c0d-4363-81a2-27b9ccfb6476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#keuntungan-kbs')]</value>
      <webElementGuid>2e676d4d-8bbd-4b1e-9191-241e2bd0a8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/ul/li/a</value>
      <webElementGuid>5fb1435e-b24f-4a84-ab30-3998d3cf1c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'keuntungan-kbs-tab' and @href = '#keuntungan-kbs' and (text() = '
KEUNTUNGAN KLUB GENERASI MAJU ' or . = '
KEUNTUNGAN KLUB GENERASI MAJU ')]</value>
      <webElementGuid>c046af87-a527-4da0-b8d2-1705483d3c4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
