<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MEKANISME KLUB GENERASI MAJU</name>
   <tag></tag>
   <elementGuidId>12f2c6bd-5210-4db9-a3b0-a922c6f4d12d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mekanisme-kbs-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mekanisme-kbs-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>26fc865e-a798-43c1-91a5-a486af727a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link mekanisme-kbs</value>
      <webElementGuid>bfa7f578-5972-4d3b-a302-c9ee2735b3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mekanisme-kbs-tab</value>
      <webElementGuid>391f8e54-1446-42f1-9431-7f84fe3f6512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>90f76414-1c7b-405a-a9aa-93e8ad69033b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#mekanisme-kbs</value>
      <webElementGuid>2bde9a1d-8890-4bf8-8e49-0c753035acef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>868d2b2d-bfb8-4933-bbd8-79614e9832bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mekanisme-kbs</value>
      <webElementGuid>7334d83c-b45f-488e-b55f-dc0f3fbf56e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b23d7c8f-0594-4e01-b89a-03f3ba5461b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
MEKANISME KLUB GENERASI MAJU </value>
      <webElementGuid>d382e652-e792-43f6-bb1c-dd0ea43eb587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mekanisme-kbs-tab&quot;)</value>
      <webElementGuid>5b775385-25cf-4d0e-9be7-242ea9c11a82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mekanisme-kbs-tab']</value>
      <webElementGuid>132c4721-49b0-4cd4-9edc-8a81dc478639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li[2]/a</value>
      <webElementGuid>77b378e1-f65b-49ef-8b00-3082802a3907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MEKANISME KLUB GENERASI MAJU')]</value>
      <webElementGuid>b9b4a483-e171-426c-8c58-b9122eb12fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keuntungan Klub Generasi Maju'])[1]/following::a[1]</value>
      <webElementGuid>34dee39b-81a5-4d5b-a401-a82a3c31fd13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bergabunglah di Klub Generasi Maju!'])[1]/following::a[2]</value>
      <webElementGuid>835b3977-ff63-4930-a938-354c8b1b349f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGM Eksplor 1+'])[2]/preceding::a[1]</value>
      <webElementGuid>1b9612f6-23fb-4c8f-ae3d-89a744b7122c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Klub Generasi Maju'])[1]/preceding::a[1]</value>
      <webElementGuid>8cab4357-7945-45d4-8384-4d30c84f3e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MEKANISME KLUB GENERASI MAJU']/parent::*</value>
      <webElementGuid>e9a73678-159b-40fc-8061-ba1338488b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#mekanisme-kbs')]</value>
      <webElementGuid>22cf6d33-d2fc-4afd-a907-db66ecded1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[7]/div/div/ul/li[2]/a</value>
      <webElementGuid>acc36726-c914-4b3d-a1d4-4aeb425961f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'mekanisme-kbs-tab' and @href = '#mekanisme-kbs' and (text() = '
MEKANISME KLUB GENERASI MAJU ' or . = '
MEKANISME KLUB GENERASI MAJU ')]</value>
      <webElementGuid>f4983704-c03c-4a2d-a4d2-69f0a6b45692</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
