<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MEKANISME KLUB GENERASI MAJU</name>
   <tag></tag>
   <elementGuidId>99c5f202-d618-461a-be6a-4707d05405f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mekanisme-kbs-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mekanisme-kbs-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a77796d2-e570-4dbd-b00a-e63d2a41dea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link mekanisme-kbs</value>
      <webElementGuid>c3092a85-a449-402f-a5ad-edfc45631242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mekanisme-kbs-tab</value>
      <webElementGuid>ec010398-ed85-4c3e-828d-634b75fbf426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>99449adb-a931-447f-92d1-da43274eef4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#mekanisme-kbs</value>
      <webElementGuid>778fc6dc-4703-40d0-b591-7f29e715f5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>8c128335-b2b5-4715-b7dc-ad2675eb5391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mekanisme-kbs</value>
      <webElementGuid>02cbbed5-9c2f-41ed-bb7c-3cab6f1d7ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1190fb6a-ff4c-43bd-b2a4-2f54717fdcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
MEKANISME KLUB GENERASI MAJU </value>
      <webElementGuid>3517d5d2-7669-4e12-ac2d-96cb82fba138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mekanisme-kbs-tab&quot;)</value>
      <webElementGuid>62a9b229-fcb8-48cf-8cc7-f08b1699390e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mekanisme-kbs-tab']</value>
      <webElementGuid>28043888-3b67-4387-b7ce-537a1fef32f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li[2]/a</value>
      <webElementGuid>ec4c4e1c-23cf-40a5-9d91-5353470da5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MEKANISME KLUB GENERASI MAJU')]</value>
      <webElementGuid>08d0d756-0203-4bb4-ab05-1537552d664c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KEUNTUNGAN KLUB GENERASI MAJU'])[1]/following::a[1]</value>
      <webElementGuid>1f375eb8-5340-4292-81a2-efd80803b6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bergabunglah di Klub Generasi Maju!'])[1]/following::a[2]</value>
      <webElementGuid>4b28598a-4463-4fef-b5ac-8c62cc3225da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dapatkan Poin Ekstra'])[1]/preceding::a[1]</value>
      <webElementGuid>d41bcceb-4cc2-44ea-b6ca-b6f7484aa826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGM EKSPLOR'])[1]/preceding::a[1]</value>
      <webElementGuid>1173dc8b-e12d-4db6-a18c-c2ef6acd6833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MEKANISME KLUB GENERASI MAJU']/parent::*</value>
      <webElementGuid>4c6cb236-39c5-4673-8323-88264f6af327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#mekanisme-kbs')]</value>
      <webElementGuid>c6b8179a-c57e-48a4-985a-9662f3bb43c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/ul/li[2]/a</value>
      <webElementGuid>10faa940-6dcb-4ce7-9708-fbdcc0753295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'mekanisme-kbs-tab' and @href = '#mekanisme-kbs' and (text() = '
MEKANISME KLUB GENERASI MAJU ' or . = '
MEKANISME KLUB GENERASI MAJU ')]</value>
      <webElementGuid>5d3ada99-d3a4-41fa-828b-82fbafa00eff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
