<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_150 gr</name>
   <tag></tag>
   <elementGuidId>4d9c872c-0831-44a5-b0dc-85c86ff5163a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;setGramasi(286929);changeVariantModal(32,'','coklat');changeVariantGramasi(32,'','coklat');&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gramasiList > button.btn.btn-product.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dfc1c548-c39f-4c82-9db9-e778ae295a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setGramasi(286929);changeVariantModal(32,'','coklat');changeVariantGramasi(32,'','coklat');</value>
      <webElementGuid>41a79c81-2549-4ef2-aefa-96941a065b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-product active</value>
      <webElementGuid>862a0854-da51-4249-94c8-71e63d3898c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>150 gr</value>
      <webElementGuid>a8d90f3b-f6c4-4623-a6cb-82ece7cc86b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gramasiList&quot;)/button[@class=&quot;btn btn-product active&quot;]</value>
      <webElementGuid>123c28be-2c17-4958-bc27-d4041c65ad60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;setGramasi(286929);changeVariantModal(32,'','coklat');changeVariantGramasi(32,'','coklat');&quot;]</value>
      <webElementGuid>4bc6df67-5674-4152-b0b7-eec46918ab2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gramasiList']/button</value>
      <webElementGuid>7b7e017d-9236-485f-808a-c78c6af49792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rasa Stroberi'])[1]/following::button[1]</value>
      <webElementGuid>71589fd6-4ed9-4519-aeb5-6d1b37c511ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rasa Coklat'])[1]/following::button[2]</value>
      <webElementGuid>f85f2ecc-d656-4783-b38c-e6485f86d02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coba Lezatnya SGM Bunda Di Sini'])[1]/preceding::button[2]</value>
      <webElementGuid>6b6c8ea6-d43c-42ec-86d7-5c6dfcaa88f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disclaimer'])[1]/preceding::button[3]</value>
      <webElementGuid>0a6326ad-ee67-40e3-ad56-92c5770188ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='150 gr']/parent::*</value>
      <webElementGuid>ce59dbc6-0142-49ee-9f43-461b91c238f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div[2]/div[2]/div/div/button</value>
      <webElementGuid>f16031ea-4ca3-4928-b928-8889a13a478b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '150 gr' or . = '150 gr')]</value>
      <webElementGuid>81ff4645-2b75-426f-8784-aef356d069aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
