<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button X floating banner</name>
   <tag></tag>
   <elementGuidId>6b456e56-49b6-4353-b22b-aa8c4783b98a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.close.close-floating-iconic > i.fa.fa-times.color-red</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-floating']/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>47fcc37a-626d-459f-9ac8-f6da7a3bffb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times color-red</value>
      <webElementGuid>1c9f5d2f-5801-412c-b850-dfd07c77b1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7ee43832-9df4-4d70-8071-b42abcaf42da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-floating&quot;)/div[@class=&quot;all&quot;]/div[@class=&quot;close close-floating-iconic&quot;]/i[@class=&quot;fa fa-times color-red&quot;]</value>
      <webElementGuid>a9474d68-1466-4678-8fb2-cc303ee99029</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-floating']/div/div/i</value>
      <webElementGuid>63d95b6c-158b-4617-967f-127b9f175424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/i</value>
      <webElementGuid>31ed5dc2-0d06-49da-87c9-1f8423a40304</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
