<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button tutup disclaimer</name>
   <tag></tag>
   <elementGuidId>a7a65a33-8696-4942-9e83-ad0e02f7fc61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-disclaimer']/div/div/div/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.box-footer > a.btn.btn-rounded.btn-lg.btn-custom-red</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c07c72d4-b399-4466-ac12-457e580771b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>b2553b87-9eb4-4ccb-92e8-74747c3f252a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>22d5a86a-b020-4f83-8d49-c4928074219b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-rounded btn-lg btn-custom-red</value>
      <webElementGuid>4073bea7-ac4a-4b32-ad0b-dfb24d62772a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
TUTUP
</value>
      <webElementGuid>dc314de4-7b01-4d2b-ad05-e756d760b4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-disclaimer&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;box-footer&quot;]/a[@class=&quot;btn btn-rounded btn-lg btn-custom-red&quot;]</value>
      <webElementGuid>41c3d225-9372-45d0-ba47-e569681ab426</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-disclaimer']/div/div/div/div[3]/a</value>
      <webElementGuid>ab210119-80ed-4551-9f6a-861767209fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'TUTUP')]</value>
      <webElementGuid>0f402c88-b3d1-4b2f-8e9f-998ec0e2dcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASI TERBAIK BAGI BAYI'])[1]/following::a[1]</value>
      <webElementGuid>506fe319-46f6-4659-b45a-c45969e0a82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BELI SEKARANG'])[1]/following::a[2]</value>
      <webElementGuid>e901db7a-318a-46a0-80c8-1a4590008a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Channel'])[1]/preceding::a[2]</value>
      <webElementGuid>6529b6fa-f8a9-4fee-8530-c4bfcc540ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Commerce'])[1]/preceding::a[3]</value>
      <webElementGuid>f74a28a3-42a2-4a8e-b72b-5da4b29d2a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TUTUP']/parent::*</value>
      <webElementGuid>8c244903-c7ce-427c-ad61-e6434677bd59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>1e5e3b6f-9e64-493c-b24d-e4ad4b6de524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/a</value>
      <webElementGuid>7ff044a6-9a4e-49f4-9552-60b638a29fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = '
TUTUP
' or . = '
TUTUP
')]</value>
      <webElementGuid>454a1dd8-d437-4573-85b0-93b5bf01f5e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
