<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button X web push</name>
   <tag></tag>
   <elementGuidId>37993ec7-57af-4b75-9c3d-e44d7eddceac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='NC_CLOSE_ICON']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NC_CLOSE_ICON</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'NC_CLOSE_ICON' and @href = 'javascript:void(0);' and (text() = 'X' or . = 'X') and @ref_element = 'Object Repository/Produk page/iframe_concat(id(, , preview-notification-frame, , ))_preview-notification-frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f549669-6fa5-427e-8ba5-ce53cac79d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NC_CLOSE_ICON</value>
      <webElementGuid>87ede2a1-5b5f-4457-a74e-a81eec138329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>3c321eca-8b0d-4a0b-9c1d-c872a25f3aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>smt-close smt-close-diy close smt-close-icon</value>
      <webElementGuid>a66189a9-de81-448b-b239-fe14da96c2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>ffc9c20c-8bd1-4eec-ae52-629d9c132fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NC_CLOSE_ICON&quot;)</value>
      <webElementGuid>c3bf26cd-34db-4148-9c0c-4f610bfef434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Produk page/iframe_concat(id(, , preview-notification-frame, , ))_preview-notification-frame</value>
      <webElementGuid>8a553e61-0677-4230-ac5b-1be2e805c69f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='NC_CLOSE_ICON']</value>
      <webElementGuid>d8f30ffe-bcc5-4f73-bccd-3acc3887337b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'X')]</value>
      <webElementGuid>9ae627c6-6524-40c5-ba1e-6a5cded32c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AMBIL DI SINI'])[1]/following::a[1]</value>
      <webElementGuid>9c474ea7-6d77-4cde-886b-9a16c194e588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'NC_CLOSE_ICON', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>b99da7e5-6526-4cf7-9862-45a1b62d0a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='X']/parent::*</value>
      <webElementGuid>1b73f488-f86e-4138-879e-78c1de91a893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>a3d1b2f5-6a57-453a-9abe-397aca0c75db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/a</value>
      <webElementGuid>2314d672-c34f-4fe6-ab1d-360ad194ffff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'NC_CLOSE_ICON' and @href = 'javascript:void(0);' and (text() = 'X' or . = 'X')]</value>
      <webElementGuid>e0675c9b-a305-4ccd-ba36-e83b66307015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
