<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button X floating banner</name>
   <tag></tag>
   <elementGuidId>6b456e56-49b6-4353-b22b-aa8c4783b98a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.close.close-floating-iconic > i.fa.fa-times.color-red</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-floating']/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>66c3be22-79aa-4fac-aa12-e2af039c935e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times color-red</value>
      <webElementGuid>25ea05de-cb2b-4881-be09-ab414f61a67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>41e61a30-ed7d-4b4d-864d-f10007aca6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-floating&quot;)/div[@class=&quot;all&quot;]/div[@class=&quot;close close-floating-iconic&quot;]/i[@class=&quot;fa fa-times color-red&quot;]</value>
      <webElementGuid>81e38f05-30cf-42bb-b0de-96095b819a6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-floating']/div/div/i</value>
      <webElementGuid>d5080405-542e-47d1-a1d5-119e3e20c252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/i</value>
      <webElementGuid>2804fc29-c85a-4059-9904-c2461a8229f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
