<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_700gr</name>
   <tag></tag>
   <elementGuidId>cd0c0101-009f-463e-8b91-8a27cb34a58f</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;setGramasi(286934);changeVariantModal(171,'','madu');changeVariantGramasi(171,'','madu');&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '700gr' or . = '700gr')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1613ef6-c1e2-4206-b9ca-2dc52b6632b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setGramasi(286934);changeVariantModal(171,'','madu');changeVariantGramasi(171,'','madu');</value>
      <webElementGuid>20eb4278-c2c0-4831-8a6b-b0778eff6fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-product</value>
      <webElementGuid>a74a4161-5d24-4033-9248-2c40f267b7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>700gr</value>
      <webElementGuid>c9da0fe4-c30f-4665-a7a6-5741645fce17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gramasiList&quot;)/button[@class=&quot;btn btn-product&quot;]</value>
      <webElementGuid>ecac3915-5b5c-4f0f-93c8-4ed18971831a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;setGramasi(286934);changeVariantModal(171,'','madu');changeVariantGramasi(171,'','madu');&quot;]</value>
      <webElementGuid>843d3015-29ff-4b43-803f-fd1a4ee9d04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gramasiList']/button[2]</value>
      <webElementGuid>df9bc6e9-cf7a-4a67-ae1e-dbe3a882a899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rasa Vanilla'])[1]/following::button[2]</value>
      <webElementGuid>b477ec52-29ed-4515-8667-b180165b3cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rasa Madu'])[1]/following::button[3]</value>
      <webElementGuid>03a4ee2a-6163-4a7f-9842-850ac896a314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BELI SGM EKSPLOR ISOPRO SOY DI SINI'])[1]/preceding::button[1]</value>
      <webElementGuid>c3784f6f-3ecb-4cef-b4c5-bff9a60ec6e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disclaimer'])[1]/preceding::button[2]</value>
      <webElementGuid>ddc22d36-8789-4c65-9a54-39ec79bc4812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='700gr']/parent::*</value>
      <webElementGuid>139f6a21-662b-487c-a4b8-03a2ada40cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/button[2]</value>
      <webElementGuid>9c994ec4-107a-4733-b4b6-e0e218540906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '700gr' or . = '700gr')]</value>
      <webElementGuid>74fd5f8b-5e1e-486e-a781-3650574fbfe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
