<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>floatingBannerWA</name>
   <tag></tag>
   <elementGuidId>e6090f2f-6fee-4608-9154-11e0f11d2619</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;popup banner&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-popup']/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ea1711a7-7d32-4c30-a45c-acdfa4defb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/FSMP/FA_FSMP-POSM_Resize-Pop-up-CC-Desktop.jpg</value>
      <webElementGuid>15e72535-15fc-462b-9fa2-206d76679591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>popup banner</value>
      <webElementGuid>56435cf1-c504-4c0c-8e92-4af71d6e5bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>popup banner</value>
      <webElementGuid>a7af838e-c98c-4811-bbcc-08ebe9df425f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>24309e0c-3972-48cd-a536-2dbea63e3034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-popup&quot;)/div[@class=&quot;all&quot;]/a[1]/div[@class=&quot;image image-product-popup desktop&quot;]/img[1]</value>
      <webElementGuid>9c2a05eb-b4ba-4e51-9a0b-cec515507c84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-popup']/div/a/div/img</value>
      <webElementGuid>d5b60ef4-5aa7-4de0-9b8e-80362a02e481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='popup banner']</value>
      <webElementGuid>e3a9830f-b574-45d3-8f51-e2bc4bd56117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>42d94f7e-b03f-4f0f-aef7-500ebe9c714c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/FSMP/FA_FSMP-POSM_Resize-Pop-up-CC-Desktop.jpg' and @alt = 'popup banner' and @title = 'popup banner']</value>
      <webElementGuid>ea2b9a56-c184-4d41-b542-40b95bebd205</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
