<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>floatingBanner</name>
   <tag></tag>
   <elementGuidId>8ae61bba-39c4-425d-b1f1-77fcd721a90e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;floating banner&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-floating']/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9866942f-daa6-444a-9307-7cb5908bcd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/FSMP/FA_FSMP-POSM_Resize-Banner-Desktop.jpg</value>
      <webElementGuid>d57c68f5-5d0f-45b2-9acb-2e6d9f86eef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>floating banner</value>
      <webElementGuid>9c55d785-9954-40e4-8689-24b3bc3cea57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>floating banner</value>
      <webElementGuid>dc0dec09-424a-441f-a1af-59b10ff0cf1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>8419c7df-02b8-4cd8-b063-6c2f8d6d97db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-floating&quot;)/div[@class=&quot;all&quot;]/div[@class=&quot;image image-product-floating desktop&quot;]/img[1]</value>
      <webElementGuid>add7bab2-f389-4eed-be9e-08ae6cc62e7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-floating']/div/div[2]/img</value>
      <webElementGuid>905623f0-73b0-4790-ab86-d8710fa6332b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='floating banner']</value>
      <webElementGuid>4e41f9b1-c5c7-4f28-a7fd-a349eb41406a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/img</value>
      <webElementGuid>37574376-cf30-47af-a8f2-a68c669a0598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/FSMP/FA_FSMP-POSM_Resize-Banner-Desktop.jpg' and @alt = 'floating banner' and @title = 'floating banner']</value>
      <webElementGuid>e481438e-6259-4870-8227-b76a5dad479d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
