<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon produk</name>
   <tag></tag>
   <elementGuidId>4fd88c2b-b943-4969-843d-6afa5584e7d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;SGM Eksplor 1+ dengan IronC&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-container']/div/div[2]/section/div/div/div/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d58dec50-711a-4a36-aaad-930090a189ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>8ce427fa-a2e8-4f7f-943f-066f206b5a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/Product%20Revamp/sgm%20compress/image-thumb__337328__product-landing-list-image-desktop/Group%2013478@3x.webp</value>
      <webElementGuid>f4beaf87-6ff8-44f1-9fd3-f7a9956d8d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>SGM Eksplor 1+ dengan IronC</value>
      <webElementGuid>7f7a070b-9266-4902-a159-7b6978a7c140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SGM Eksplor 1+ dengan IronC</value>
      <webElementGuid>db2dcc7a-2590-4b74-97e5-c29938c1f70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-container&quot;)/div[@class=&quot;product-revamp&quot;]/div[@class=&quot;pimcore_area_product-landing-list pimcore_area_content&quot;]/section[@class=&quot;product&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;product__row&quot;]/div[@class=&quot;product__col&quot;]/a[1]/picture[1]/img[1]</value>
      <webElementGuid>d46051f9-b390-48e9-8b4f-93e612796cb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-container']/div/div[2]/section/div/div/div/a/picture/img</value>
      <webElementGuid>d4ef3312-4847-4816-a51c-7a8748cc3e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='SGM Eksplor 1+ dengan IronC']</value>
      <webElementGuid>145451b7-8496-4f7b-8e8b-4da9337a0c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/picture/img</value>
      <webElementGuid>5f22f50f-4635-457d-a4b4-9190e829bf0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dncgty1mvp6vd.cloudfront.net/Product%20Revamp/sgm%20compress/image-thumb__337328__product-landing-list-image-desktop/Group%2013478@3x.webp' and @alt = 'SGM Eksplor 1+ dengan IronC' and @title = 'SGM Eksplor 1+ dengan IronC']</value>
      <webElementGuid>b5b7d2f0-46ae-4740-b22f-7458b030e481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
