<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , preview-notification-frame, , ))_preview-notification-frame</name>
   <tag></tag>
   <elementGuidId>34a92c77-8400-488f-9562-378e4d8d385e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='preview-notification-frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#preview-notification-frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1b78bdfd-dbd0-4573-b783-f78084632bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preview-notification-frame</value>
      <webElementGuid>2ef17efa-7201-42b8-96d9-3969e1ba551e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>st_preview_frame_banner</value>
      <webElementGuid>e3963bf1-8849-40ab-b3e6-dc0e4bdae032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preview-notification-frame</value>
      <webElementGuid>2849b059-07f5-447c-900c-618c47ebc321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>90086d05-607d-41c3-872e-d86b9dc7c90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d13d3d07-18c0-4e29-a99c-8941724f8f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>08efac76-3c8d-48f9-a241-65ee48229f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preview-notification-frame&quot;)</value>
      <webElementGuid>b14f3698-8fdf-4e14-8040-cbc490a05bf6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
