<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe____st_preview_frame_bpn</name>
   <tag></tag>
   <elementGuidId>00f645d8-a0e1-4f52-bc8a-b74ab617b4b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__st_fancy_popup']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.__st_preview_frame_bpn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>31cee89a-a109-4f18-bd53-79987f8f99db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>__st_preview_frame_bpn</value>
      <webElementGuid>29a7331a-f25b-4d84-bce1-b858547c5d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>fd6ee111-b095-43cc-8af0-ab24e8e9bccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fb9be55f-7607-4779-a0f2-6d672e1ed210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__st_fancy_popup&quot;)/iframe[@class=&quot;__st_preview_frame_bpn&quot;]</value>
      <webElementGuid>639ca086-aa4b-4f4b-bb29-b8abe0d52723</webElementGuid>
   </webElementProperties>
</WebElementEntity>
