<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (3)</name>
   <tag></tag>
   <elementGuidId>c0880f89-9512-4678-8d51-ad26706178d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-container']/div/section/ul/li[7]/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e78ff19b-87f0-490a-b348-9b291fa41f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/product%20optigrow/image-thumb__501338__product-revamp-thumbnail-category-product/gain-%20icon%20ats.webp</value>
      <webElementGuid>e64d4adc-5e6f-46b4-9c7c-ed762d922c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>c3de370f-7f29-4512-a2fa-70ac05432a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>27bad721-890c-4052-ad9d-668514a87882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>86</value>
      <webElementGuid>7b21f78f-86d9-4db2-9ce9-a61b74d3165a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-container&quot;)/div[@class=&quot;product-detail-revamp&quot;]/section[@class=&quot;product-top&quot;]/ul[@class=&quot;product-top__list&quot;]/li[@class=&quot;product-top__item&quot;]/a[1]/picture[1]/img[1]</value>
      <webElementGuid>beffe13d-6a34-433b-8ead-89e1237054b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-container']/div/section/ul/li[7]/a/picture/img</value>
      <webElementGuid>ee7fab16-bd3c-4fec-9609-3525ac36305d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/picture/img</value>
      <webElementGuid>5b4fbf23-536f-41f3-a481-30f6040fe881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/product%20optigrow/image-thumb__501338__product-revamp-thumbnail-category-product/gain-%20icon%20ats.webp']</value>
      <webElementGuid>b5e91059-7a0f-4e47-baa5-21e05e0d5fb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
