<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (2)</name>
   <tag></tag>
   <elementGuidId>c4918b9b-c360-48ff-af44-31d3219336b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-container']/div/section/ul/li[6]/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>03c931a1-dc52-4e4a-90a0-f32f4d8a7ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/product/products/image-thumb__593579__product-revamp-thumbnail-category-product/Pack%20Isopro%20Soy%20%28366x481%29-01.webp</value>
      <webElementGuid>7d692941-79c7-42ad-88ae-c342b39a08e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>4dd95d7d-b25a-4249-9b94-b7fb69979e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>e8924d92-a591-4d2d-996c-fa4852e65bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>86</value>
      <webElementGuid>d31cc452-30d9-42a2-8a91-defa1d9ae675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-container&quot;)/div[@class=&quot;product-detail-revamp&quot;]/section[@class=&quot;product-top&quot;]/ul[@class=&quot;product-top__list&quot;]/li[@class=&quot;product-top__item&quot;]/a[1]/picture[1]/img[1]</value>
      <webElementGuid>a85ce97b-a113-47a9-ba27-d16c2e6aaae7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-container']/div/section/ul/li[6]/a/picture/img</value>
      <webElementGuid>bff97daf-e4b8-4f9c-8ebb-93a79aa7dc53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/picture/img</value>
      <webElementGuid>6128a0f7-e493-4243-9889-cf74f1514543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/product/products/image-thumb__593579__product-revamp-thumbnail-category-product/Pack%20Isopro%20Soy%20%28366x481%29-01.webp']</value>
      <webElementGuid>1fc14bc6-2b84-4ece-bcfd-5d19e7713036</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
