<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (1)</name>
   <tag></tag>
   <elementGuidId>c7853d27-4cec-4d77-b716-e5669831e5d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-container']/div/section/ul/li[2]/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ddedaed9-a010-4043-80ee-54d926f4a25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/product/products/image-thumb__268339__product-revamp-thumbnail-category-product/3plus.webp</value>
      <webElementGuid>6dc29516-500a-484a-8ab7-addba1a4ce54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>578b6aea-9e0a-4faa-9652-75f5081adeb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>4ff1f024-0a3a-4aed-b735-33599d33726f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>86</value>
      <webElementGuid>8c73bad3-1e07-47fe-855e-22d37fadcf1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-container&quot;)/div[@class=&quot;product-detail-revamp&quot;]/section[@class=&quot;product-top&quot;]/ul[@class=&quot;product-top__list&quot;]/li[@class=&quot;product-top__item&quot;]/a[1]/picture[1]/img[1]</value>
      <webElementGuid>98543d16-b4c1-446f-8de3-5349e2d184df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-container']/div/section/ul/li[2]/a/picture/img</value>
      <webElementGuid>dfd65228-bcae-4255-88ec-f82ef8e57db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/picture/img</value>
      <webElementGuid>4da4d868-0b0f-458b-9270-c0fa4c1f09f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/product/products/image-thumb__268339__product-revamp-thumbnail-category-product/3plus.webp']</value>
      <webElementGuid>9e9bc34b-698d-40fc-a0ca-168b060bb431</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
