<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_prosoy</name>
   <tag></tag>
   <elementGuidId>95906551-d10c-4763-9de4-86319d1ea6c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-container']/div/div[2]/section/div/div/div[6]/a/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;SGM EKSPLOR ISOPRO SOY&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>64333560-2977-4e2e-8fbd-dcde7ea6889f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>6242324a-a670-4dfa-9bfb-7b57960bda73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/_default_upload_bucket/image-thumb__595995__product-landing-list-image-desktop/Tumbnail%20Website%20Product%20Isoprosoy.webp</value>
      <webElementGuid>2b043b5d-160a-44c2-8612-6e2045459c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>SGM EKSPLOR ISOPRO SOY</value>
      <webElementGuid>9a539934-af26-4772-aa00-68eaa4279e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SGM EKSPLOR ISOPRO SOY</value>
      <webElementGuid>21b14ce6-56b5-4e62-bb47-c2d5d5ef779a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-container&quot;)/div[@class=&quot;product-revamp&quot;]/div[@class=&quot;pimcore_area_product-landing-list pimcore_area_content&quot;]/section[@class=&quot;product&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;product__row&quot;]/div[@class=&quot;product__col&quot;]/a[1]/picture[1]/img[1]</value>
      <webElementGuid>0d15f5ea-59d8-4186-9ac6-5cb59b7c8f2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-container']/div/div[2]/section/div/div/div[6]/a/picture/img</value>
      <webElementGuid>f9ebc407-d8aa-4cbe-bd82-1a20e8047e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='SGM EKSPLOR ISOPRO SOY']</value>
      <webElementGuid>b3b8776a-8ff1-4d4a-a08d-8875960ae99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a/picture/img</value>
      <webElementGuid>9fc92b89-e39e-4c6a-b2dc-436e387a7739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dncgty1mvp6vd.cloudfront.net/_default_upload_bucket/image-thumb__595995__product-landing-list-image-desktop/Tumbnail%20Website%20Product%20Isoprosoy.webp' and @alt = 'SGM EKSPLOR ISOPRO SOY' and @title = 'SGM EKSPLOR ISOPRO SOY']</value>
      <webElementGuid>43f2efaf-7d4a-4aa7-b78b-9e2a1edcdd6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
