<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , __st_bpn_no, , ))_notnow</name>
   <tag></tag>
   <elementGuidId>399c3027-68f6-4265-b903-2c90eb22ee78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__st_bpn_no']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__st_bpn_no</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @name = 'notnow' and @id = '__st_bpn_no' and @ref_element = 'Object Repository/Produk page/iframe____st_preview_frame_bpn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>899ee8da-a5ea-4602-b6a1-20f968807428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6a8acfb-3d82-4c0d-99ac-ca38065880f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notnow</value>
      <webElementGuid>748c0f7e-a26e-4a0d-8ff0-060efe1e4e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__st_bpn_no</value>
      <webElementGuid>017e1822-ddee-4766-ae9c-3fae8a58a9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NANTI</value>
      <webElementGuid>36c0d589-b663-42ef-bd16-c403dd11421d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__st_bpn_no&quot;)</value>
      <webElementGuid>fc048d67-98d5-4504-a298-c30b14e6b4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Produk page/iframe____st_preview_frame_bpn</value>
      <webElementGuid>a3dd7825-2de5-4689-ac2a-d71a85591770</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__st_bpn_no']</value>
      <webElementGuid>e348466d-4e68-4ba5-8841-8a5e89a874d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>159464e8-506e-4eb9-b7e6-1d46fb762cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'notnow' and @id = '__st_bpn_no']</value>
      <webElementGuid>059ebb36-ef41-43c3-8c62-8dd1ada9f0ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
