<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_5 PLUS</name>
   <tag></tag>
   <elementGuidId>fee2628c-a096-4ca9-91e4-1eb9a961d022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-container']/div/section/ul/li[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6027cb4e-37ce-4af0-97de-09b2c04a106e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5 PLUS</value>
      <webElementGuid>8f0f429f-4740-4beb-af51-b0717f2d8018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-container&quot;)/div[@class=&quot;product-detail-revamp&quot;]/section[@class=&quot;product-top&quot;]/ul[@class=&quot;product-top__list&quot;]/li[@class=&quot;product-top__item&quot;]/a[1]/span[1]</value>
      <webElementGuid>5f4b53d3-ad61-477d-8cae-1163fe366588</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-container']/div/section/ul/li[3]/a/span</value>
      <webElementGuid>f91a4e07-5d72-4557-aa23-58661e6bce3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGM Eksplor 3+'])[1]/following::span[3]</value>
      <webElementGuid>906f41af-1374-405b-b73e-cc086cc8d3a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[1]/following::span[3]</value>
      <webElementGuid>7926d544-0083-48f6-bf47-e7fc3ecd9ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Family'])[1]/preceding::span[1]</value>
      <webElementGuid>ab44ea03-4cb5-403e-b218-1ca080eed4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUNDA'])[1]/preceding::span[2]</value>
      <webElementGuid>8b2b3505-eeff-4bd4-856e-39de88de9f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5 PLUS']/parent::*</value>
      <webElementGuid>d80f238b-102f-420a-ae09-7d14bb3f1fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/ul/li[3]/a/span</value>
      <webElementGuid>901bdaff-0231-4db8-9495-05f5f83e3894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '5 PLUS' or . = '5 PLUS')]</value>
      <webElementGuid>068565c0-fd82-4a6b-8a4b-748a8fe81507</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
