<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kalkulator Kehamilan</name>
   <tag></tag>
   <elementGuidId>35a91939-5207-4ed0-ac3f-e7e8ddc1b091</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='dropdownAgm']/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87ed6808-5c80-444d-a5cb-b6c8e0a038dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>7c700503-206d-4f20-88d5-88ebf50bd770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.generasimaju.co.id/tools/kalkulator-kehamilan</value>
      <webElementGuid>79d72e7b-c4ef-4056-99a6-721fb3d42f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kalkulator Kehamilan</value>
      <webElementGuid>8877c45a-5383-46aa-a1e5-a7cacad5d40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/nav[@class=&quot;navbar navbar-default navbar-fixed-top&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;wrap wrap-menu&quot;]/div[@class=&quot;lower-menu&quot;]/div[@class=&quot;desktop-nav hidden-sm hidden-xs&quot;]/ul[@class=&quot;nav navbar-nav nav-justified&quot;]/li[@id=&quot;dropdownAgm&quot;]/div[@class=&quot;dropdown-menu&quot;]/ul[@class=&quot;menu-vertical&quot;]/li[1]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>a19e9eb7-1a14-4e66-939c-8d9acae921ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='dropdownAgm']/div/ul/li/a</value>
      <webElementGuid>ce429709-824c-4b9b-8054-b3c17e202b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kalkulator Kehamilan')]</value>
      <webElementGuid>93489fa9-72bb-4b2a-84d7-26138601d5da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diary Generasi Maju'])[1]/preceding::a[1]</value>
      <webElementGuid>3e1aad63-3860-433a-a052-f6b21af97793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cek Risiko Tidak Cocok Susu Sapi'])[1]/preceding::a[2]</value>
      <webElementGuid>88fef8b2-a222-40e0-ba7c-2a7495bee9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kalkulator Kehamilan']/parent::*</value>
      <webElementGuid>31844659-160c-433c-93be-d71234716b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.generasimaju.co.id/tools/kalkulator-kehamilan')]</value>
      <webElementGuid>547a48a9-7fea-4479-b491-35b1eee16e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/ul/li/a</value>
      <webElementGuid>255b0ce2-ef4a-4927-9b67-52b3d5dea199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.generasimaju.co.id/tools/kalkulator-kehamilan' and (text() = 'Kalkulator Kehamilan' or . = 'Kalkulator Kehamilan')]</value>
      <webElementGuid>65fe4a3b-01ae-4e61-9ce9-7f8b4a5d9217</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
