<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>banner daftar disini</name>
   <tag></tag>
   <elementGuidId>76dc19f9-e646-4316-923f-428c7b99a966</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a > picture > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='banner-offering-dgm']/div/section/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f36b962b-ee76-43c1-b45f-83d26fdcf63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>e70773bc-9cd7-4eea-a37b-f90b2d1436a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>94403132-409e-44e1-9e94-bea8c881da3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_default_upload_bucket/image-thumb__595421__webp/Banner%20NONMPASI%20-%2028%20Aug%20%5BDesktop%5D_1.webp</value>
      <webElementGuid>c5041e9f-f477-448d-a2b7-7beb1aa42a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>9f3b7725-c70a-4982-b80a-097078d3ae9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;banner-offering-dgm&quot;)/div[@class=&quot;container&quot;]/section[@class=&quot;banner-bottom&quot;]/a[1]/picture[1]/img[1]</value>
      <webElementGuid>813669e8-425c-4e78-b122-de02608bc482</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='banner-offering-dgm']/div/section/a/picture/img</value>
      <webElementGuid>7b5d17ac-bc1e-4648-be47-31d3846bf7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/picture/img</value>
      <webElementGuid>fb623eee-2983-4cb3-bb70-334ac61e208d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_default_upload_bucket/image-thumb__595421__webp/Banner%20NONMPASI%20-%2028%20Aug%20%5BDesktop%5D_1.webp']</value>
      <webElementGuid>6b9597be-27bd-4214-a887-f8121fab51f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
