<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SIMPAN</name>
   <tag></tag>
   <elementGuidId>7e9b7493-11b4-4039-975f-46251008726d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submit-calc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submit-calc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>001ced51-eb3c-4ce3-89f3-f5fae194f2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa4ee36b-9a60-42ae-bc32-6865e9ad7380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-calc</value>
      <webElementGuid>52887503-b8ea-4fe9-982b-0bbd09092881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setDate()</value>
      <webElementGuid>86682b23-5e60-447c-b9f1-b52d91576ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-emboss-red-calc</value>
      <webElementGuid>9e207758-37b0-420f-bb3b-f6887b915730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SIMPAN  →</value>
      <webElementGuid>a0014f31-a787-415b-8a16-4c85fdbe0c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-content&quot;)/div[@class=&quot;footer-modal&quot;]/button[@id=&quot;submit-calc&quot;]</value>
      <webElementGuid>4a40a4ae-5df0-4363-b074-ee6fa7457993</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submit-calc']</value>
      <webElementGuid>6c2a4e63-7ca9-41f2-93e0-e7a8cd4f37b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-content']/div[2]/button</value>
      <webElementGuid>6fe20d55-9c2d-4489-81a6-fee8f9b8f2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun*'])[1]/following::button[1]</value>
      <webElementGuid>64c264d2-82b3-4a3c-8e93-5f70d13cd1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desember'])[1]/following::button[1]</value>
      <webElementGuid>bedc1192-3073-4be5-9a3e-d0f7a2738f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tanggal HPHT'])[2]/preceding::button[1]</value>
      <webElementGuid>3c01836f-9f80-4a1d-a90f-1f642ed0eaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal*'])[2]/preceding::button[1]</value>
      <webElementGuid>40fee11b-77e1-48be-8226-8c359d3734fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SIMPAN  →']/parent::*</value>
      <webElementGuid>e3e03cc2-4a4d-41a9-900f-ff66bb05bc5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>39574d5a-0ac5-44cc-916e-5a03cc49cb1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'submit-calc' and (text() = 'SIMPAN  →' or . = 'SIMPAN  →')]</value>
      <webElementGuid>15842d57-e207-4bda-9bef-cda5d560c447</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
