<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SIMPAN</name>
   <tag></tag>
   <elementGuidId>7e9b7493-11b4-4039-975f-46251008726d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submit-calc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submit-calc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a06d277-2bcf-4497-8c4e-4594df203e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e7b886b-418c-4981-b326-0ca547768e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-calc</value>
      <webElementGuid>48b12964-82aa-43f0-81c9-109999ca2d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setDate()</value>
      <webElementGuid>46b6e88f-e3c0-47cf-a344-643c94541a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-emboss-red-calc</value>
      <webElementGuid>7ba06fd4-4fa6-4487-b31f-ddf564e38db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SIMPAN  →</value>
      <webElementGuid>ed26b826-6030-42e8-af40-562205fa900c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-content&quot;)/div[@class=&quot;footer-modal&quot;]/button[@id=&quot;submit-calc&quot;]</value>
      <webElementGuid>7c8f2a83-cc79-4ab2-84b9-e092bf1bb296</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submit-calc']</value>
      <webElementGuid>5cbe2cbc-0560-46d8-ab7a-b35f3a5e3039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-content']/div[2]/button</value>
      <webElementGuid>4457a6e0-2472-4f31-bdf0-2e5dc65ea0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun*'])[1]/following::button[1]</value>
      <webElementGuid>c3eae78d-11cf-40d5-840f-881fda666802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desember'])[1]/following::button[1]</value>
      <webElementGuid>3d79097e-bb5a-45f8-a633-b335aef9f098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tanggal HPHT'])[2]/preceding::button[1]</value>
      <webElementGuid>e70db0fd-520c-4bc5-89ce-251ec42ba7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal*'])[2]/preceding::button[1]</value>
      <webElementGuid>1ade7489-5c7e-43a2-b68c-0505c4c8d6bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SIMPAN  →']/parent::*</value>
      <webElementGuid>5092361d-2616-40a7-8605-36eaa61c70ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>410a0355-aaf0-4e78-b711-693e7f83b617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'submit-calc' and (text() = 'SIMPAN  →' or . = 'SIMPAN  →')]</value>
      <webElementGuid>bb5d460f-e183-4c84-a4ad-44719be25316</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
