<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kehamilan Bulan ke 8</name>
   <tag></tag>
   <elementGuidId>4e7e3fa0-9da4-40a4-96cf-3f4cc2ce68d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tabk2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tabk2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f41f9c6-497f-41e1-986c-9399326fac40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-kehamilan</value>
      <webElementGuid>de0434da-e352-4162-8899-192e2da87fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabk2</value>
      <webElementGuid>0339a44e-d28f-45fd-a7f3-724570e05f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>activateTab('tabk2')</value>
      <webElementGuid>5ac4c199-91cf-43d3-b288-a7ce2e5f6573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kehamilan Bulan ke 8</value>
      <webElementGuid>845d6b26-f99c-4632-b68d-18fc5636ead2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabk2&quot;)</value>
      <webElementGuid>1a5ab7dd-f4cf-4edd-b5f0-d8dffbcca579</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tabk2']</value>
      <webElementGuid>79534179-b3a0-4666-825a-f74d0a97c161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-container']/section/div[4]/div[2]/button[2]</value>
      <webElementGuid>89032dd6-945a-4e12-832c-abb27ace6e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kehamilan Bulan ke 7'])[1]/following::button[1]</value>
      <webElementGuid>59dccbf2-89fb-472c-8fac-20b2d0cd1f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kumpulan informasi, tips &amp; nutrisi seputar kehamilan'])[1]/following::button[2]</value>
      <webElementGuid>fca0271a-9438-4a52-aeac-2b81728a71a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kehamilan Bulan ke 9'])[1]/preceding::button[1]</value>
      <webElementGuid>48a55011-1f99-471e-bce9-d2ce8eaece73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artikel Populer'])[1]/preceding::button[2]</value>
      <webElementGuid>d5fa8e27-25d4-46e5-9f9b-7229db45508c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kehamilan Bulan ke 8']/parent::*</value>
      <webElementGuid>93ab8523-55cf-4202-a95c-f789fd61d62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>0be7c863-0d11-4688-b816-1e1ebd1802ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'tabk2' and (text() = 'Kehamilan Bulan ke 8' or . = 'Kehamilan Bulan ke 8')]</value>
      <webElementGuid>f0203357-364b-4f2f-9fea-ab0f3ddae784</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
