<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button card next</name>
   <tag></tag>
   <elementGuidId>7fe1a9f4-0658-428a-bcf4-327a1197ff5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.slick-next-new.slick-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b3efff4b-b013-424e-8e94-09e8cbd4c32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-next-new slick-arrow</value>
      <webElementGuid>fb7911cb-559a-4f7d-8ccc-9b4b387b9577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>b5000351-2788-4dcf-bae2-7d1021503794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dcc699cb-2bf2-4a4c-9ed4-668b3213b9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;diary-generasi-maju&quot;)/div[@class=&quot;pimcore_area_fitur-tumbuh-kembang pimcore_area_content&quot;]/div[@class=&quot;fitur-tumbuh-kembang&quot;]/div[@class=&quot;container&quot;]/section[@class=&quot;content-fitur&quot;]/div[@class=&quot;row&quot;]/button[@class=&quot;slick-next-new slick-arrow&quot;]</value>
      <webElementGuid>7188d0a7-f1ab-480a-b75e-b97a207e6b77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>7f21fc60-3db1-4bc7-86f8-6a69f96e29fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='diary-generasi-maju']/div[2]/div/div/section[2]/div/button[2]</value>
      <webElementGuid>8a94b02d-ece9-4468-a865-8b57659f4655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>7061e7bc-91b6-46ae-8cff-70bb35e954be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>6afe7a21-ceae-4234-a916-9fdfd72a9692</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
