<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kehamilan Bulan ke 8</name>
   <tag></tag>
   <elementGuidId>4e7e3fa0-9da4-40a4-96cf-3f4cc2ce68d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabk2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tabk2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee8ca589-983a-4d33-90f5-4f84ae7ff169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-kehamilan</value>
      <webElementGuid>70c0a102-2781-458d-8f32-82eee73f38ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabk2</value>
      <webElementGuid>2076a69a-6291-452d-a883-19c3ca512e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>activateTab('tabk2')</value>
      <webElementGuid>d8d94b4f-03d7-4f3f-add2-6cfd414e991e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kehamilan Bulan ke 8</value>
      <webElementGuid>d78fafcb-d776-4e13-a16e-4eb5cfaafbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabk2&quot;)</value>
      <webElementGuid>2b80d14c-a948-4a06-8ee0-7b4d97cef1cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tabk2']</value>
      <webElementGuid>32cb9de1-9839-43b9-9f78-2033fa27b117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-container']/section/div[4]/div[2]/button[2]</value>
      <webElementGuid>80e0d483-c0c6-4db6-96c1-66dbdd0880d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kehamilan Bulan ke 7'])[1]/following::button[1]</value>
      <webElementGuid>b9c8860e-d312-4e7e-a137-c939dca0db74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kumpulan informasi, tips &amp; nutrisi seputar kehamilan'])[1]/following::button[2]</value>
      <webElementGuid>36cbedaa-d50b-4ecd-81de-25c874370856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kehamilan Bulan ke 9'])[1]/preceding::button[1]</value>
      <webElementGuid>20f4c635-8686-4a6d-91b5-59cb064dc2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artikel Populer'])[1]/preceding::button[2]</value>
      <webElementGuid>312409c2-89d5-43a2-8123-c3a472d806e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kehamilan Bulan ke 8']/parent::*</value>
      <webElementGuid>e59dbb40-2195-4a00-bc10-dfdc29fa6c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>fbf48622-6ce3-42bf-afba-7de3a995d437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'tabk2' and (text() = 'Kehamilan Bulan ke 8' or . = 'Kehamilan Bulan ke 8')]</value>
      <webElementGuid>e964418f-b5fb-4a86-9300-6c58ffac8370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
