<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_MULAI DISINI</name>
   <tag></tag>
   <elementGuidId>2768342b-ba7f-4121-b5bf-1f6a70bf88b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-mulai']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-mulai</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c191c040-0e07-4752-8b54-0d314dbf6de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>081bfcbc-23d8-43cd-b63e-8cea4dcb2333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-emboss-red</value>
      <webElementGuid>66ff635c-2f41-4298-b23c-34b4b87fdae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-mulai</value>
      <webElementGuid>f75ede82-469a-4f46-9d7e-0ae2d81d4c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MULAI DISINI →</value>
      <webElementGuid>e24d8b9e-4aac-450d-9c0a-afd1deeb9c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-mulai&quot;)</value>
      <webElementGuid>d9c0b5e0-6d12-49b8-b8b4-687b22e85534</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-mulai']</value>
      <webElementGuid>a2cc4a7d-6976-48cf-9c49-debb38f9a12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='kalkulator-kehamilan']/div/div/form/button</value>
      <webElementGuid>4cf2ebb5-e380-40dd-bc04-e640ad594903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hari Pertama Haid Terakhir (HPHT)*'])[1]/following::button[1]</value>
      <webElementGuid>ecaf24a9-e517-4000-999b-6f038bd7f25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kalkulator Kehamilan'])[4]/following::button[1]</value>
      <webElementGuid>5ab62aeb-1d85-4c37-a15c-d9b91363c2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::button[1]</value>
      <webElementGuid>60ccca22-bc2d-43ae-ba66-11f2ec47bda7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tanggal HPHT'])[1]/preceding::button[1]</value>
      <webElementGuid>89ca64f2-6f1f-4a15-a48e-bb0d77b752c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MULAI DISINI →']/parent::*</value>
      <webElementGuid>c447a736-8df1-48f8-9980-3e4b2a77f3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>c6235a98-d5da-49b1-a485-0d717ccdc850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btn-mulai' and (text() = 'MULAI DISINI →' or . = 'MULAI DISINI →')]</value>
      <webElementGuid>f8ce0d0d-2222-4fea-99cb-050ccdb836b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
