<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kehamilan Bulan ke 9</name>
   <tag></tag>
   <elementGuidId>c7f7e732-930d-40ca-a67c-c8354bae2422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tabk3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tabk3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a7db33a2-4390-490c-a297-e89c0f52a59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-kehamilan</value>
      <webElementGuid>b9aa48c9-7e05-4a2f-aa58-741df7bdf365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabk3</value>
      <webElementGuid>56a625e1-d14f-4405-914f-1d53ba22345a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>activateTab('tabk3')</value>
      <webElementGuid>2a1dee5f-0b55-4340-b5e8-c5870701e1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kehamilan Bulan ke 9</value>
      <webElementGuid>347a328d-3b34-4907-83a1-d2abdd35bf18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabk3&quot;)</value>
      <webElementGuid>4d297a49-e9b2-40ac-9f16-40b8b74d5774</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tabk3']</value>
      <webElementGuid>7013a0a1-f52f-4960-ba77-1a39eba5882c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-container']/section/div[4]/div[2]/button[3]</value>
      <webElementGuid>832c2428-9d95-4d1f-9653-7948c48e8125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kehamilan Bulan ke 8'])[1]/following::button[1]</value>
      <webElementGuid>a3d94d4d-c5a5-4a7c-ab7e-8e50056b001f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kehamilan Bulan ke 7'])[1]/following::button[2]</value>
      <webElementGuid>9895b43d-66dd-43f9-b4c6-6108dc051b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artikel Populer'])[1]/preceding::button[1]</value>
      <webElementGuid>15cb2966-e7ac-4a85-a6e2-c9543571b1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/preceding::button[1]</value>
      <webElementGuid>8f5a4402-de15-41d5-a859-d67118c29509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kehamilan Bulan ke 9']/parent::*</value>
      <webElementGuid>0282089d-95b5-4be5-abe2-798bf3f15517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>fcaf21ed-0bb1-4b4a-8bc8-439d42f876cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'tabk3' and (text() = 'Kehamilan Bulan ke 9' or . = 'Kehamilan Bulan ke 9')]</value>
      <webElementGuid>1d26ae94-ff4b-4540-a636-1bde9fbafc10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
