<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button card prev</name>
   <tag></tag>
   <elementGuidId>e160478f-05b3-42c7-b4f0-e488285b71ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.slick-prev-new.slick-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c13252b-20f7-42ab-96bb-4fb5ecc3d2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-prev-new slick-arrow</value>
      <webElementGuid>14a141f7-1521-4440-978e-4e69c3cc2018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Previous</value>
      <webElementGuid>5de895fb-011c-438d-a6c0-f35a931dd29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f4c8fb00-691a-40b2-ac7f-66017296b983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;diary-generasi-maju&quot;)/div[@class=&quot;pimcore_area_fitur-tumbuh-kembang pimcore_area_content&quot;]/div[@class=&quot;fitur-tumbuh-kembang&quot;]/div[@class=&quot;container&quot;]/section[@class=&quot;content-fitur&quot;]/div[@class=&quot;row&quot;]/button[@class=&quot;slick-prev-new slick-arrow&quot;]</value>
      <webElementGuid>7497eb6b-1131-436b-84cb-6b334b44bf00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>6582fbc2-f587-4a91-8c30-651f488f5fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='diary-generasi-maju']/div[2]/div/div/section[2]/div/button</value>
      <webElementGuid>6079d225-69d7-41d6-9062-fcaaba7d3b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/button</value>
      <webElementGuid>6bb1aeb8-df81-412a-89fa-bf47bbb0529a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>55737c33-9c83-46c1-91d7-4aee12fffc0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
