<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kehamilan Bulan ke 9</name>
   <tag></tag>
   <elementGuidId>c7f7e732-930d-40ca-a67c-c8354bae2422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabk3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tabk3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>36ecb3fb-2459-4491-be4d-53446a46a856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-kehamilan</value>
      <webElementGuid>691b7283-a7b1-40ef-843b-0e6d3de18dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabk3</value>
      <webElementGuid>ec53fe9d-0216-47d2-bc7f-c604e50cdcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>activateTab('tabk3')</value>
      <webElementGuid>1436e292-3266-4e21-b742-84832814f59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kehamilan Bulan ke 9</value>
      <webElementGuid>22140490-7176-43af-9de3-dcd2c561a912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabk3&quot;)</value>
      <webElementGuid>2c9985f8-fa90-4e5a-b769-99076cc2d914</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tabk3']</value>
      <webElementGuid>fa980618-fd0d-40dc-987c-631cd44a7899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-container']/section/div[4]/div[2]/button[3]</value>
      <webElementGuid>5d27c178-c1a3-467a-8072-a1a8760d193e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kehamilan Bulan ke 8'])[1]/following::button[1]</value>
      <webElementGuid>4dd25def-7011-47d5-94f6-e708dff19aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kehamilan Bulan ke 7'])[1]/following::button[2]</value>
      <webElementGuid>d5a675d2-2df3-44ac-bd97-85b07a139afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artikel Populer'])[1]/preceding::button[1]</value>
      <webElementGuid>23388b63-08f7-4cbe-9171-4f4890517c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/preceding::button[1]</value>
      <webElementGuid>651a288d-594b-4db5-a3a7-5c57b15cfe7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kehamilan Bulan ke 9']/parent::*</value>
      <webElementGuid>0a657503-0ade-440f-9c8a-3dc56b316068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>43f7754f-6c71-4d0b-ab5b-a29cc741a3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'tabk3' and (text() = 'Kehamilan Bulan ke 9' or . = 'Kehamilan Bulan ke 9')]</value>
      <webElementGuid>dc97db14-8b8a-487e-a034-4b8d77726b3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
