<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Usia Kehamilan_innerBar</name>
   <tag></tag>
   <elementGuidId>a9ed126e-69b2-4986-9603-08cc27ab2bcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trim1-ot-2 > div.innerBar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='trim1-ot-2']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c57da769-dc15-4101-9a13-f8f548d001ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>innerBar</value>
      <webElementGuid>989d5f48-b871-4769-a2fc-f8c060defb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trim1-ot-2&quot;)/div[@class=&quot;innerBar&quot;]</value>
      <webElementGuid>16e9e8d7-4ea2-48d6-bb75-985212955644</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trim1-ot-2']/div</value>
      <webElementGuid>8ed96d43-9173-4c85-a5d2-d52173e9e8d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div</value>
      <webElementGuid>bd2e2600-fba3-4125-8c3b-3f6db514fc9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
