<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Lupa Password_a-22rz3qja75vg</name>
   <tag></tag>
   <elementGuidId>021a0809-90b2-4d42-822f-4edf35696192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-22rz3qja75vg&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-22rz3qja75vg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5b3fe517-3548-41f3-bfe3-f38f5faba902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>9ef07be1-cacc-4e60-982b-45ddc2639500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>5adc76cc-d8d6-41f2-a510-423ccdc1bc40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>86c350e5-8901-4d0d-a540-130434df89b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>f56ed59a-1fce-4151-bbca-f751bb030f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-22rz3qja75vg</value>
      <webElementGuid>a0cdb971-4ed4-4043-b09c-6a2a424a5641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5c869715-8845-4378-a9ca-a79a2f8bcb04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>effbacb4-861b-488e-806d-9a691896d5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>279e7242-9521-464e-ad4c-6d51ccc3a6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LftmnAnAAAAAMTumcEwTocK9Djnu-gt_rOoVmFC&amp;co=aHR0cHM6Ly93d3cuZ2VuZXJhc2ltYWp1LmNvLmlkOjQ0Mw..&amp;hl=id&amp;v=u-xcq3POCWFlCr3x8_IPxgPu&amp;theme=light&amp;size=normal&amp;cb=uv7za4tfgtei</value>
      <webElementGuid>7a747251-98f0-4067-ac6e-f923a054c785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha-login&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>bd549885-0e7c-41ec-8ca5-1dce95da6d60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-22rz3qja75vg']</value>
      <webElementGuid>d27a7a44-d632-4c33-9ec0-a06c16bf0169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha-login']/div/div/iframe</value>
      <webElementGuid>cbe88e3e-019b-40f4-9101-07d45d791f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>08368b1c-d64d-4993-8fd8-7b3a4f0379d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-22rz3qja75vg' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LftmnAnAAAAAMTumcEwTocK9Djnu-gt_rOoVmFC&amp;co=aHR0cHM6Ly93d3cuZ2VuZXJhc2ltYWp1LmNvLmlkOjQ0Mw..&amp;hl=id&amp;v=u-xcq3POCWFlCr3x8_IPxgPu&amp;theme=light&amp;size=normal&amp;cb=uv7za4tfgtei']</value>
      <webElementGuid>09a9dc3e-8c39-46ae-8e88-3e185707c00c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
