<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_Nomor Handphone_msisdn</name>
   <tag></tag>
   <elementGuidId>5192432c-a403-4232-9759-2c75a38623ed</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phone-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f4c6bb8-fb09-4d59-a98a-661386544545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>msisdn</value>
      <webElementGuid>d598c160-d40b-4a09-b7df-310f101e78c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>df082f3a-d072-415e-8275-4d319dc6d4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone-number</value>
      <webElementGuid>2de20483-7cbe-4b76-95a0-dbcde3cfa9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control kgm__form--input w-100</value>
      <webElementGuid>b55385b8-13a2-4d18-8642-bed38e8994f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nomor Handphone</value>
      <webElementGuid>7b04949a-a583-4442-809b-1ddb8fb338de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone-number&quot;)</value>
      <webElementGuid>3e68f866-38b0-4bc3-a89c-489c7807e4d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone-number']</value>
      <webElementGuid>9d938fcf-ea23-41db-9042-8167af2aaee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-login']/div[2]/input</value>
      <webElementGuid>1e086397-e1b8-422d-984c-1298e50dbeb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5fe55a01-32df-48a6-b31f-ae91c55d6294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'msisdn' and @type = 'number' and @id = 'phone-number' and @placeholder = 'Masukkan Nomor Handphone']</value>
      <webElementGuid>84226e0e-038b-44f1-a355-d94d26b8d20e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
