<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_Nomor Handphone_msisdn</name>
   <tag></tag>
   <elementGuidId>5192432c-a403-4232-9759-2c75a38623ed</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone-number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phone-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1fea3e8-d208-4819-ac05-688cff4055da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>msisdn</value>
      <webElementGuid>7ba39c40-957c-4cc2-a143-4d1385884f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e54f8d98-c9bc-48ad-91f0-f4470fc583b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone-number</value>
      <webElementGuid>75dd304d-c433-40c4-b80c-f507f5bb677b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control kgm__form--input w-100</value>
      <webElementGuid>d2e9759a-3675-4432-886c-7d3093999c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nomor Handphone</value>
      <webElementGuid>01eb7ec3-0181-457f-b79e-0523c74bab66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone-number&quot;)</value>
      <webElementGuid>aff879e7-cf24-4433-a41b-2699d3ed222a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone-number']</value>
      <webElementGuid>7ec9b51f-5942-4f05-9bdd-b96b5db12148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-login']/div[2]/input</value>
      <webElementGuid>2ee4df74-c641-48d0-b92b-506531a0915a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>cec7a0e5-64e8-4581-bed7-24c0b7e092fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'msisdn' and @type = 'number' and @id = 'phone-number' and @placeholder = 'Masukkan Nomor Handphone']</value>
      <webElementGuid>4db10a8b-11bd-48b7-a213-19c41cbe889b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
