<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Baca Selengkapnya_1_2_3_4_5_6_7_8</name>
   <tag></tag>
   <elementGuidId>87e7535b-a60e-453f-8781-4ae328c76986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-ke-3']/div/div/div[2]/div/div[3]/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4f5bb133-7348-42a0-b2f9-60effc78d2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/artikel/0-3-bulan/perawatan-bayi/cara-menyendawakan-bayi</value>
      <webElementGuid>33cb6d7b-bebb-4b2c-9b77-5ee535224a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baca Selengkapnya ></value>
      <webElementGuid>e45f4103-8d09-46c8-b478-764b0366f0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-ke-3&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 big-box-left-with-list&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;wrap-hot-artikel&quot;]/div[@class=&quot;wrap-list-img-left&quot;]/div[@class=&quot;txt-art&quot;]/div[@class=&quot;r-more&quot;]/a[2]</value>
      <webElementGuid>b2fe15ef-9d71-4106-aa8a-f0f242d67088</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-ke-3']/div/div/div[2]/div/div[3]/div/div/a[2]</value>
      <webElementGuid>a85daafa-d260-435f-a7bc-43a76ab01b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Baca Selengkapnya >')])[15]</value>
      <webElementGuid>9bbf147e-a8e0-4e96-848a-fe9ca4a77d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perawatan Bayi'])[3]/following::a[2]</value>
      <webElementGuid>ba933fe9-4ba4-4a5f-a513-d6493bb195ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara Mudah Menyendawakan Bayi Setelah...'])[1]/following::a[2]</value>
      <webElementGuid>c174e1d3-240c-402c-8150-927dcdf7c5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resep'])[7]/preceding::a[2]</value>
      <webElementGuid>d5466b8a-14a5-4ad3-89de-6a3fe6106937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Selengkapnya'])[3]/preceding::a[2]</value>
      <webElementGuid>4702a225-b4cb-4950-84e5-fe8f269f7fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/artikel/0-3-bulan/perawatan-bayi/cara-menyendawakan-bayi')])[4]</value>
      <webElementGuid>fadfb5b3-7c81-4cab-8640-aa18ec4f8044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div[3]/div/div/a[2]</value>
      <webElementGuid>73291d97-8f9d-4d0a-a4b9-74ac197c0173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/artikel/0-3-bulan/perawatan-bayi/cara-menyendawakan-bayi' and (text() = 'Baca Selengkapnya >' or . = 'Baca Selengkapnya >')]</value>
      <webElementGuid>263a648b-4935-45f3-be5f-11acfe6d85a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
