<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Baca Selengkapnya_1</name>
   <tag></tag>
   <elementGuidId>46775a77-b90e-4bb1-b3b9-b985c63d6f3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-ke-1']/div/div/div[2]/div/div[2]/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>28b08866-40d9-4d6f-8124-d65353f021dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/artikel/1-tahun/stimulasi/stimulasi-anak-1-tahun</value>
      <webElementGuid>dc7f11f8-774e-428a-a29d-addea3bca3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baca Selengkapnya ></value>
      <webElementGuid>a4f33ac7-7f8a-45f7-a60c-c703a11ef980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-ke-1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 big-box-left-with-list&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;wrap-hot-artikel&quot;]/div[@class=&quot;wrap-list-img-left&quot;]/div[@class=&quot;txt-art&quot;]/div[@class=&quot;r-more&quot;]/a[2]</value>
      <webElementGuid>039ffb4b-8e23-4af7-85f5-1f20739328e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-ke-1']/div/div/div[2]/div/div[2]/div/div/a[2]</value>
      <webElementGuid>940e2eee-2a46-4476-a0c6-06eff69a9c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Baca Selengkapnya >')])[4]</value>
      <webElementGuid>9181c581-5d17-411e-acde-6ab4723857d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stimulasi'])[2]/following::a[2]</value>
      <webElementGuid>295b5c4a-44b4-4001-bd95-e00e136f855f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baca Selengkapnya >'])[3]/following::a[4]</value>
      <webElementGuid>c577ed04-e86e-483d-819b-0893f62ff877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kenali Gejala DBD pada Anak,...'])[1]/preceding::a[2]</value>
      <webElementGuid>97b191ad-2e3d-42cb-a2f2-4ae9dc6864a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kesehatan'])[1]/preceding::a[2]</value>
      <webElementGuid>71853545-2e23-401a-95ca-d7481c610f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/artikel/1-tahun/stimulasi/stimulasi-anak-1-tahun')])[4]</value>
      <webElementGuid>67806e30-122f-4c21-8f66-48c08fd2d89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/a[2]</value>
      <webElementGuid>e8ef025f-0d8b-4f86-9f24-2bb4fea5388a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/artikel/1-tahun/stimulasi/stimulasi-anak-1-tahun' and (text() = 'Baca Selengkapnya >' or . = 'Baca Selengkapnya >')]</value>
      <webElementGuid>b233df15-a91a-480e-82a2-34837822494e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
