<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn Lihat Selengkapnya resep</name>
   <tag></tag>
   <elementGuidId>9f4d943c-44e9-4f47-8f41-1fdc3bb9735c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-ke-1']/div[3]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-high-red.btn-lg.btn-padding-100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>874469da-6411-452c-bead-30d495886eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-high-red btn-lg btn-padding-100</value>
      <webElementGuid>ebf8be6f-554c-4ca1-a04c-a63f9102652e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/artikel?slug=anak</value>
      <webElementGuid>3a1eec90-b2b3-4930-8f86-f173bc9b6f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f38d31dd-d658-4caa-be9f-f2d855fce981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aba5888a-bb3c-4508-bbfd-a2817178f3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Selengkapnya</value>
      <webElementGuid>34a2b8db-56d9-4908-a25d-c6a56d34c787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-ke-1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 text-center margin-top-40&quot;]/a[@class=&quot;btn btn-high-red btn-lg btn-padding-100&quot;]</value>
      <webElementGuid>46b6016e-dfad-47f7-8e01-71d99ed30225</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-ke-1']/div[3]/div/a</value>
      <webElementGuid>f1dfe546-7ab3-4c20-93af-699dcabe762d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lihat Selengkapnya')]</value>
      <webElementGuid>2380f5f2-03f0-46bc-a07e-d99f120d735e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anak'])[4]/following::a[1]</value>
      <webElementGuid>cb44f302-ab91-4a15-9925-a44ec76e4516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vanilla Guava Milkshake'])[1]/following::a[1]</value>
      <webElementGuid>f5a82f4c-0da1-49ae-a1d7-1e861633bda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trimester 1'])[1]/preceding::a[1]</value>
      <webElementGuid>c37723f7-499e-48df-88df-1fce1490cb44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Janin &amp; Kandungan'])[1]/preceding::a[1]</value>
      <webElementGuid>f48f8001-b992-4186-aa37-f83ac3264c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Selengkapnya']/parent::*</value>
      <webElementGuid>8b3adb6a-af14-4534-a061-0e1b9bd80a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/artikel?slug=anak')]</value>
      <webElementGuid>e6684ff6-c9dc-46f8-b038-d83b0a9b2401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>da8de77e-7bd0-4e11-8a3f-0a3a33aaedb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/artikel?slug=anak' and (text() = 'Lihat Selengkapnya' or . = 'Lihat Selengkapnya')]</value>
      <webElementGuid>faa6a8c3-5769-411e-a138-7a9357cdb95e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
