<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button nanti</name>
   <tag></tag>
   <elementGuidId>56da1134-6bc0-44ec-a34d-0023aac6ca5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__st_bpn_no']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__st_bpn_no</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>795ded92-ce7b-4439-94a6-6221a531436d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cdeb6518-53e5-4ebd-9dde-4e146d3d0e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notnow</value>
      <webElementGuid>3c8ad48e-2cd7-462f-84c0-6ebca5b40d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__st_bpn_no</value>
      <webElementGuid>ca181676-5bfe-438a-bb68-5942cdcbda2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NANTI</value>
      <webElementGuid>6ddaad47-450d-48b4-a1f6-a898ac34c29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__st_bpn_no&quot;)</value>
      <webElementGuid>ca9e3ec1-b2d5-4c8e-a1ae-d00fa95f4900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe___ nanti ambil</value>
      <webElementGuid>6c464e46-cc39-441f-adb0-5c64ef4bac91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__st_bpn_no']</value>
      <webElementGuid>129face1-6701-46f1-be73-4a1050b1b632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>eaf21b5c-5aa8-4b08-95a3-135b9763067f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'notnow' and @id = '__st_bpn_no']</value>
      <webElementGuid>5c7addce-a850-40cd-bad3-7c5397c43b06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
