<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe___ nanti ambil</name>
   <tag></tag>
   <elementGuidId>696dbb2c-fcc0-49b9-ace5-9478d057548a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__st_fancy_popup']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.__st_preview_frame_bpn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c02d7a43-7c77-427b-b378-fdd05273feaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>__st_preview_frame_bpn</value>
      <webElementGuid>e3f30089-b0a4-41b6-a49e-9c8cb63506eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5291bbff-5452-4b6b-88e0-798d9eb6091c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7ada6ffd-d603-45af-a930-3a44dea35329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__st_fancy_popup&quot;)/iframe[@class=&quot;__st_preview_frame_bpn&quot;]</value>
      <webElementGuid>93d783e0-ee2b-4412-bf89-22efe80f9b0b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
