<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (1)</name>
   <tag></tag>
   <elementGuidId>6e66a63a-9dac-43f4-83b2-bf62b6e18cf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide01']/a/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slick-slide01 > a > picture > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1fc529a5-b616-4e25-9dbe-a7bb446e2380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>68846a25-798e-4b57-a80a-2c148d32fab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>9fb3e878-be47-4990-a95d-e3149dea65ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/background-slider/image-thumb__594660__banner-image-thumbnail/Home%20Page%20Banner_%2015%20mei%202023-1_1.webp</value>
      <webElementGuid>efcc675c-c31b-41bd-a2d5-896662357fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1280</value>
      <webElementGuid>1e29f3b9-9e93-4f1a-9cee-5d277f182fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>cbf791aa-1b53-4c44-a030-7e243deb1453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/background-slider/image-thumb__594660__banner-image-thumbnail/Home%20Page%20Banner_%2015%20mei%202023-1_1.webp</value>
      <webElementGuid>78460219-a635-40c5-a940-b1cf18debf36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide01&quot;)/a[1]/picture[1]/img[1]</value>
      <webElementGuid>813ed1c7-39f0-457e-bbe4-fb0665fbd3b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slick-slide01']/a/picture/img</value>
      <webElementGuid>0d48f2aa-2622-4dc7-8a70-f5a8a1d657a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dncgty1mvp6vd.cloudfront.net/background-slider/image-thumb__594660__banner-image-thumbnail/Home%20Page%20Banner_%2015%20mei%202023-1_1.webp')]</value>
      <webElementGuid>eebc7a44-a224-406a-9db7-da18bd089df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/picture/img</value>
      <webElementGuid>cc56f5b6-6ed8-4794-b74d-5dd62df07a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dncgty1mvp6vd.cloudfront.net/background-slider/image-thumb__594660__banner-image-thumbnail/Home%20Page%20Banner_%2015%20mei%202023-1_1.webp']</value>
      <webElementGuid>7dec5b68-f77e-4ea3-a3e8-a705903c6ea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
