<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>7ec21b48-8d78-4f50-8995-7b53f2ab1fa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide02']/a/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Lucky Wheel&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5987d364-30a4-4ce7-95ca-71c67c8b09ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>80a569f7-71f4-4cf0-90df-b2d8c9eecd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>77b42035-f8f0-4c1b-b626-c678d8f45fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/background-slider/image-thumb__593903__banner-image-thumbnail/Homepage%20Hero%20Banner_Desktop.webp</value>
      <webElementGuid>7c60f5cc-94a3-4368-9c0f-be980dd12c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Lucky Wheel</value>
      <webElementGuid>9d5b8bec-c1a9-4763-921a-b5c2952e97e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Lucky Wheel</value>
      <webElementGuid>420b7778-67a9-4719-ac69-4aa8352bab21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1280</value>
      <webElementGuid>5b1689ce-72aa-4afe-8183-59e700e5497c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>cc156a30-9ebf-4da5-847b-974b19b39f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/background-slider/image-thumb__593903__banner-image-thumbnail/Homepage%20Hero%20Banner_Desktop.webp</value>
      <webElementGuid>b16a9d2a-2ee2-4234-9144-a59120936dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide02&quot;)/a[1]/picture[1]/img[1]</value>
      <webElementGuid>8de090a6-689d-4f18-8b1f-340af308450f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slick-slide02']/a/picture/img</value>
      <webElementGuid>d24f206e-1f0e-4dec-9189-38f71cbb6cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Lucky Wheel']</value>
      <webElementGuid>bea6d5f2-81d9-479b-acd5-e14d7c78f68b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/picture/img</value>
      <webElementGuid>9a3770c5-8b32-4957-9129-6cda103b87ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Lucky Wheel' and @title = 'Lucky Wheel' and @src = 'https://dncgty1mvp6vd.cloudfront.net/background-slider/image-thumb__593903__banner-image-thumbnail/Homepage%20Hero%20Banner_Desktop.webp']</value>
      <webElementGuid>1a5a3342-f1b9-4a26-bcf7-495499a200d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
