<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Kehamilan  Menyusui_icon-hamil</name>
   <tag></tag>
   <elementGuidId>bf881a14-e6e8-42fc-994e-e4007a7f7aa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='myTab']/li[3]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.txt-orange > img.icon-hamil</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0d2e4c65-d8c5-4203-8e5c-876450ab32d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/assets/images/tabbing/tab-2-active.png</value>
      <webElementGuid>a45cb8f9-1088-485e-bfaf-2f1727b0ab8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Icon Bayi</value>
      <webElementGuid>322b4624-cf76-4b9c-a387-70a009ee13ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>28ca2511-d493-44d3-9838-291ee41876de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-hamil</value>
      <webElementGuid>e7443573-d5c9-427f-9cce-b4cfef39fdb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32px</value>
      <webElementGuid>72777792-7825-40f9-9127-ea49bd17dd7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>48px</value>
      <webElementGuid>1413472c-0dbc-45d7-ad45-e5f01a742449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myTab&quot;)/li[@class=&quot;tab-3 bayi&quot;]/a[@class=&quot;txt-orange&quot;]/img[@class=&quot;icon-hamil&quot;]</value>
      <webElementGuid>efc063be-e696-4444-9214-aea0bb309292</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li[3]/a/img</value>
      <webElementGuid>7c11533c-42cd-4c00-bcee-26bd80daf2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Icon Bayi']</value>
      <webElementGuid>0ca2b036-f4ed-4aa5-b54c-f3b34d72a542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/img</value>
      <webElementGuid>9b4eee3a-af88-4217-aeec-f73b76c05c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dncgty1mvp6vd.cloudfront.net/assets/images/tabbing/tab-2-active.png' and @alt = 'Icon Bayi']</value>
      <webElementGuid>46d00afe-50d6-4546-acc6-9a6f8e889e79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
