<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>8d476fb2-a467-489f-9fd0-f2fb8a4368e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#slick-slide01 > a > picture > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide01']/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3c108941-129a-4fb7-91c6-472c79bfd102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2264479c-4af9-4114-a16e-6f9c9023b9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>dadd0a2a-d960-4f45-b38a-703bfd6986c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/background-slider/image-thumb__594660__banner-image-thumbnail/Home%20Page%20Banner_%2015%20mei%202023-1_1.webp</value>
      <webElementGuid>05b7c6b8-ae4b-402c-887c-bddc2f22552f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1280</value>
      <webElementGuid>8e5a4bb0-ef6b-4091-9c46-0dbe301e2cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>39195e14-cbca-44ef-8872-265d4229160f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/background-slider/image-thumb__594660__banner-image-thumbnail/Home%20Page%20Banner_%2015%20mei%202023-1_1.webp</value>
      <webElementGuid>280b226a-212d-4caf-a0a3-f0a6610daf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide01&quot;)/a[1]/picture[1]/img[1]</value>
      <webElementGuid>87f3bdcc-ba33-4083-b2c5-2dcb206981cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slick-slide01']/a/picture/img</value>
      <webElementGuid>eaefc034-704c-4132-80f8-86d60f1ca834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dncgty1mvp6vd.cloudfront.net/background-slider/image-thumb__594660__banner-image-thumbnail/Home%20Page%20Banner_%2015%20mei%202023-1_1.webp')]</value>
      <webElementGuid>ebb76c74-44f4-4047-9a6c-8cebbd01948f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/picture/img</value>
      <webElementGuid>aa9c961d-22dc-4f81-9778-cc719e896712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dncgty1mvp6vd.cloudfront.net/background-slider/image-thumb__594660__banner-image-thumbnail/Home%20Page%20Banner_%2015%20mei%202023-1_1.webp']</value>
      <webElementGuid>95cc992e-7b14-49ef-a3fa-cf2db128e8d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
