<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SAYA SETUJU_button-careline</name>
   <tag></tag>
   <elementGuidId>70b90452-d35d-4820-9f76-0bcad06c5372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.button-careline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://dncgty1mvp6vd.cloudfront.net/assets/images/floating-careline.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2f3eee5c-69de-4305-866a-0f97ed8d3ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/assets/images/floating-careline.png</value>
      <webElementGuid>18c176a2-eacc-4b17-ba6f-40833f364fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-careline</value>
      <webElementGuid>3c59448e-5721-4f06-91f8-54b87e259540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>103704d4-09a4-4cd8-a5d2-8b43edd1a768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>89</value>
      <webElementGuid>27c1139c-7fda-4f30-994d-61d077bb86fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>89</value>
      <webElementGuid>afa61ba2-2f26-400e-9114-36854d153093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>cbde1685-b5f6-43f2-90b0-109a99e0220e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/section[@class=&quot;chat-careline&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;chat-careline--button&quot;]/img[@class=&quot;button-careline&quot;]</value>
      <webElementGuid>5ae6aa18-7344-4c3a-b539-34dc664504e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dncgty1mvp6vd.cloudfront.net/assets/images/floating-careline.png')]</value>
      <webElementGuid>0420de60-7398-4222-899e-9c3045ea5c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/img</value>
      <webElementGuid>d5f3d2fc-3619-4bf2-af90-3d81d1228d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dncgty1mvp6vd.cloudfront.net/assets/images/floating-careline.png']</value>
      <webElementGuid>73282dde-3b32-4d15-9c6f-bf27c522cfc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
