<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_article resep 3</name>
   <tag></tag>
   <elementGuidId>902c0212-cda5-4892-b6d4-653263b1c46d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-ke-1']/div[2]/div[3]/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f73b5504-4041-4715-b199-19272dfe329f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/articles/article/image-thumb__592279__resep-thumbnail/1366x563_Vanilla%20Guava%20Milkshake.webp</value>
      <webElementGuid>f64a2a26-ba16-489d-8c68-f4051c2cf2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Vanilla Guava Milkshake</value>
      <webElementGuid>21f51d5d-43bb-4db4-980a-b2ceeada4fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Vanilla Guava Milkshake</value>
      <webElementGuid>33369715-4d85-4034-b783-ccfcd71cb076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>videoline-img-thumbnail lazy-image</value>
      <webElementGuid>2546dc98-1bad-4a22-abf7-48992bcfff10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>175</value>
      <webElementGuid>a0cafbd5-3e4d-4082-a0a4-46c8524bf424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>360</value>
      <webElementGuid>3250a5e5-582c-485c-a30d-2b05ef24bafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>2c242f9c-86d4-47b4-9c2f-ac4d57ea47c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-ke-1&quot;)/div[@class=&quot;row wrapper-3-produk&quot;]/div[@class=&quot;col-md-4 pull-left-15 hidden-xs&quot;]/div[@class=&quot;wrap-sample-artikel&quot;]/a[1]/div[@class=&quot;img-art thumbnail-small&quot;]/img[@class=&quot;videoline-img-thumbnail lazy-image&quot;]</value>
      <webElementGuid>6fed6d15-6957-4156-970a-15f19bc086e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-ke-1']/div[2]/div[3]/div/a/div/img</value>
      <webElementGuid>7b50fee4-6571-4848-aa70-ac455f68cc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Vanilla Guava Milkshake']</value>
      <webElementGuid>c4606c75-f3e4-459c-a40d-a579cfb29673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/div/img</value>
      <webElementGuid>8621b2fa-607f-4e0c-a1fc-c93f16685042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dncgty1mvp6vd.cloudfront.net/articles/article/image-thumb__592279__resep-thumbnail/1366x563_Vanilla%20Guava%20Milkshake.webp' and @title = 'Vanilla Guava Milkshake' and @alt = 'Vanilla Guava Milkshake']</value>
      <webElementGuid>270ad30f-973e-449f-8ebe-d99878698616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
