<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Previous_first-img-slider</name>
   <tag></tag>
   <elementGuidId>97d7438a-d997-4006-a644-9e69bb7a2ae4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide00']/a/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.first-img-slider</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>af784c69-ad18-48cb-8c1e-232fbd060c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>378d56ac-5a92-45f7-a95d-d8e13adb6254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/background-slider/image-thumb__593804__banner-image-thumbnail/%5BDesktop%5D%20Home%20Page%20Banner%20with%20CTA.webp</value>
      <webElementGuid>295c980e-6781-44b9-82f3-c9a86b9fb2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1280</value>
      <webElementGuid>c4fe5f27-1e1f-4ae1-8a58-44904c1ea286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>6c4b0d1a-a15d-4cfa-8bec-06383962a9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>first-img-slider</value>
      <webElementGuid>736b0bc6-75bb-473d-9094-6e6559cd4ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/background-slider/image-thumb__593804__banner-image-thumbnail/%5BDesktop%5D%20Home%20Page%20Banner%20with%20CTA.webp</value>
      <webElementGuid>5b386a66-b0eb-4acb-90cc-d3844e1256e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide00&quot;)/a[1]/picture[1]/img[@class=&quot;first-img-slider&quot;]</value>
      <webElementGuid>5cbab90a-5b77-4cb9-80a2-3b4c9830e725</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slick-slide00']/a/picture/img</value>
      <webElementGuid>8617a9e4-9bc1-4dad-809c-c7a734b92494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dncgty1mvp6vd.cloudfront.net/background-slider/image-thumb__593804__banner-image-thumbnail/%5BDesktop%5D%20Home%20Page%20Banner%20with%20CTA.webp')]</value>
      <webElementGuid>41bb2a18-a4f4-404c-8d59-c66265179d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>ebf4f5ff-c81f-4f0f-b80a-c5955d80629d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dncgty1mvp6vd.cloudfront.net/background-slider/image-thumb__593804__banner-image-thumbnail/%5BDesktop%5D%20Home%20Page%20Banner%20with%20CTA.webp']</value>
      <webElementGuid>51b094f2-9e2b-418d-b8f4-57831abd2522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
