<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_article resep 1</name>
   <tag></tag>
   <elementGuidId>923c83c9-91a0-4be4-b45a-7d250d8e2358</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-ke-1']/div[2]/div/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.videoline-img-thumbnail.lazy-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8e11e6ab-6239-401c-86c6-b3e4e70fada4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/articles/article/image-thumb__592312__resep-thumbnail/1366x563_Beef%20Creamy%20Curry%20Udon.webp</value>
      <webElementGuid>f769753d-a4b6-479d-a234-0c4082e15ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Beef Creamy Curry Udon</value>
      <webElementGuid>20efb1bb-7523-428b-8149-7e95fc9fad86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Beef Creamy Curry Udon</value>
      <webElementGuid>5ee31777-9f72-4574-8f67-864db7eadc2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>videoline-img-thumbnail lazy-image</value>
      <webElementGuid>6009134a-2d11-4fd8-bd61-0f0510de23e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>175</value>
      <webElementGuid>d899aa6d-9bc8-4674-a386-8b57427644f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>360</value>
      <webElementGuid>5c0c8bff-9ad6-40e4-a69d-57745ec2e8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>c92fac0f-6758-4bbd-b677-ea87879292c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-ke-1&quot;)/div[@class=&quot;row wrapper-3-produk&quot;]/div[@class=&quot;col-md-4 push-right-15&quot;]/div[@class=&quot;wrap-sample-artikel&quot;]/a[1]/div[@class=&quot;img-art thumbnail-small&quot;]/img[@class=&quot;videoline-img-thumbnail lazy-image&quot;]</value>
      <webElementGuid>e2812399-226c-4467-80d7-bd08c7d68223</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-ke-1']/div[2]/div/div/a/div/img</value>
      <webElementGuid>eb5225d2-9dae-49c2-b2e0-e13431889d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Beef Creamy Curry Udon']</value>
      <webElementGuid>8dfce2b9-a29f-4983-8e7d-47c6c1e3e013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/div/img</value>
      <webElementGuid>4cf6c189-6558-4e85-9628-a0ff6fda4d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dncgty1mvp6vd.cloudfront.net/articles/article/image-thumb__592312__resep-thumbnail/1366x563_Beef%20Creamy%20Curry%20Udon.webp' and @title = 'Beef Creamy Curry Udon' and @alt = 'Beef Creamy Curry Udon']</value>
      <webElementGuid>ae7b20cc-1cbb-4a39-8fb2-53d3b6ca8b10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
