<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , __st_bpn_no, , ))_notnow (1)</name>
   <tag></tag>
   <elementGuidId>5b916e23-894b-4c66-8149-6840c6e95606</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__st_bpn_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__st_bpn_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdbbfd93-6d51-48e5-9811-fcd749a1835f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e80768cd-f64a-4baa-a7ac-0d1f2eefb856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notnow</value>
      <webElementGuid>0aad7b25-73b3-4f8b-95ec-636fccf3a031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__st_bpn_no</value>
      <webElementGuid>a42b17ea-2f69-40d6-981d-fbc8f70775eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NANTI</value>
      <webElementGuid>f2b03dd0-993c-47b2-b639-424903bbefb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__st_bpn_no&quot;)</value>
      <webElementGuid>fd306576-24f9-45bf-8b74-795513c13bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Homepage/iframe___ nanti ambil</value>
      <webElementGuid>c4ff6ffe-69aa-4fb9-add3-1972f4786ca0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__st_bpn_no']</value>
      <webElementGuid>cdb948c6-86e1-4e88-9b62-270005a71c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7da84e9b-e2dc-4803-91e1-20fe91349191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'notnow' and @id = '__st_bpn_no']</value>
      <webElementGuid>1b0a239d-4ba3-4c40-99f6-fc22c0197598</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
