<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Promo Terpopuler_media-object image-object</name>
   <tag></tag>
   <elementGuidId>cbbadece-669c-4094-9acc-a7224a9d93b9</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promo']/div[2]/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://dncgty1mvp6vd.cloudfront.net/_default_upload_bucket/image-thumb__594606__event-promo-article-small/Thumbnail%20%5BLowres%5D_1.webp' and @title = 'PROGRAM “Submit Pertama Kali SGM Family Yummy-Nutri Dapat Gopay hingga Rp. 20.000,-”' and @alt = 'PROGRAM “Submit Pertama Kali SGM Family Yummy-Nutri Dapat Gopay hingga Rp. 20.000,-”']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.box.box-solid.box-newline-15 > div.box-body > div.media > div.media-left > a.ad-click-event > img.media-object.image-object</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>345d9d54-d0c4-478c-a910-33712218f21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/_default_upload_bucket/image-thumb__594606__event-promo-article-small/Thumbnail%20%5BLowres%5D_1.webp</value>
      <webElementGuid>a27023b2-a610-4568-ab9c-cb2b62fcc733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PROGRAM “Submit Pertama Kali SGM Family Yummy-Nutri Dapat Gopay hingga Rp. 20.000,-”</value>
      <webElementGuid>36e4309a-2578-441b-a90f-dec64c772ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>PROGRAM “Submit Pertama Kali SGM Family Yummy-Nutri Dapat Gopay hingga Rp. 20.000,-”</value>
      <webElementGuid>1542b3a4-6736-416a-b558-57ea8af1343d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>media-object image-object</value>
      <webElementGuid>e049144e-48c8-4042-b4f2-2d55c6e455dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>116</value>
      <webElementGuid>67e7abe7-6e49-4d20-9055-33fccaca8576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>116</value>
      <webElementGuid>ef351c59-316b-4aa8-bd9a-9443b66eb1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promo&quot;)/div[@class=&quot;col-lg-4 popular-article-master popular-event-promo z-2&quot;]/div[@class=&quot;box box-solid box-newline-15&quot;]/div[@class=&quot;box-body&quot;]/div[@class=&quot;media&quot;]/div[@class=&quot;media-left&quot;]/a[@class=&quot;ad-click-event&quot;]/img[@class=&quot;media-object image-object&quot;]</value>
      <webElementGuid>e1d30085-b110-40cf-8e43-3e53573a64f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='promo']/div[2]/div/div/div/div/a/img</value>
      <webElementGuid>35c84c1f-c309-4f0a-a464-bb91d90388be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='PROGRAM “Submit Pertama Kali SGM Family Yummy-Nutri Dapat Gopay hingga Rp. 20.000,-”']</value>
      <webElementGuid>3b098acb-c8d3-4754-85af-ebdd1eb67b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a/img</value>
      <webElementGuid>00279364-313f-459a-b814-fa87329c677c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dncgty1mvp6vd.cloudfront.net/_default_upload_bucket/image-thumb__594606__event-promo-article-small/Thumbnail%20%5BLowres%5D_1.webp' and @title = 'PROGRAM “Submit Pertama Kali SGM Family Yummy-Nutri Dapat Gopay hingga Rp. 20.000,-”' and @alt = 'PROGRAM “Submit Pertama Kali SGM Family Yummy-Nutri Dapat Gopay hingga Rp. 20.000,-”']</value>
      <webElementGuid>c2266ab3-ce3a-4434-a7be-9e8a131d87ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
