<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Baca Selengkapnya_media-object image-ob_19dc64</name>
   <tag></tag>
   <elementGuidId>25d48a97-4b2f-4224-90be-80fda68bf32a</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promo']/div/div[2]/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://dncgty1mvp6vd.cloudfront.net/_default_upload_bucket/image-thumb__593950__event-promo-article-medium/Push%20to%20FS_10K_Promo%20Banner.webp' and @title = 'Program “Submit Kode Unik Pertama SGM Eksplor”' and @alt = 'Program “Submit Kode Unik Pertama SGM Eksplor”']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.media-object.image-object.image-object-landscape.isdesktop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0e8dc706-572f-4263-815e-7f5556199110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dncgty1mvp6vd.cloudfront.net/_default_upload_bucket/image-thumb__593950__event-promo-article-medium/Push%20to%20FS_10K_Promo%20Banner.webp</value>
      <webElementGuid>d89a3e23-7a7c-4a7c-ab08-50026815e1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Program “Submit Kode Unik Pertama SGM Eksplor”</value>
      <webElementGuid>c13dc93a-45d0-4f64-87a6-1fdeedd83c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Program “Submit Kode Unik Pertama SGM Eksplor”</value>
      <webElementGuid>5da4b480-b36e-4afd-a0ed-a191bc548467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>media-object image-object image-object-landscape isdesktop</value>
      <webElementGuid>8643e2c2-5241-40e5-b686-b69aa1e90252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>a02a5af6-0426-4e8d-8b99-4eb44b6f4684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>58751301-5166-4c0d-a43a-2948e2e602fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promo&quot;)/div[@class=&quot;col-lg-8 article-master&quot;]/div[@class=&quot;col-md-12 box-list z-2&quot;]/div[@class=&quot;box box-solid box-newline-20&quot;]/div[@class=&quot;box-body&quot;]/div[@class=&quot;media&quot;]/div[@class=&quot;media-left&quot;]/a[@class=&quot;ad-click-event&quot;]/img[@class=&quot;media-object image-object image-object-landscape isdesktop&quot;]</value>
      <webElementGuid>c6e3bd93-10b2-48a3-9035-d0ba73a38c09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='promo']/div/div[2]/div/div/div/div/a/img</value>
      <webElementGuid>416aa821-0f32-495c-a031-964f10ea9887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Program “Submit Kode Unik Pertama SGM Eksplor”']</value>
      <webElementGuid>0a9953fa-338b-4649-a57b-790f19855ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/a/img</value>
      <webElementGuid>ecc4ab21-b6cf-4042-b052-88260230fefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dncgty1mvp6vd.cloudfront.net/_default_upload_bucket/image-thumb__593950__event-promo-article-medium/Push%20to%20FS_10K_Promo%20Banner.webp' and @title = 'Program “Submit Kode Unik Pertama SGM Eksplor”' and @alt = 'Program “Submit Kode Unik Pertama SGM Eksplor”']</value>
      <webElementGuid>5ea227d7-052d-40b0-97ac-8a84e7721858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
