<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ (1)</name>
   <tag></tag>
   <elementGuidId>10364707-f435-4f6b-a6fd-a3580b40cf37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paginationListArticle']/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.pagination > li:nth-of-type(7) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>783e9e95-7f1e-412d-a117-88930989b064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>f56a2bf6-68d8-4b86-861a-6edf258fa849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>0d8a8f27-4e29-4041-9572-e46556500805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                »
                </value>
      <webElementGuid>a0c8b66b-994f-4ac8-ae26-c5021676ff97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paginationListArticle&quot;)/ul[@class=&quot;pagination&quot;]/li[7]/a[1]</value>
      <webElementGuid>fc371ee7-4852-4143-9297-e4624a747dca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paginationListArticle']/ul/li[7]/a</value>
      <webElementGuid>d313d3ed-cc2f-4736-a9ac-de1f685b74bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baca Sekarang >'])[5]/following::a[7]</value>
      <webElementGuid>a424ded6-01b3-4190-9e68-8e5243122a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nutrisi &amp; Makanan'])[3]/following::a[7]</value>
      <webElementGuid>597d379d-e864-4cc6-a9bb-c0ec7a744f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anemia'])[4]/preceding::a[1]</value>
      <webElementGuid>35ad62fc-3af2-48a1-aefa-86fbbc4983bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[7]</value>
      <webElementGuid>84fbc287-1802-4058-b30c-51ddb83cb5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/ul/li[7]/a</value>
      <webElementGuid>774e8e1b-e557-4dde-afb6-efcf1f6dc4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = '
                »
                ' or . = '
                »
                ')]</value>
      <webElementGuid>1185a34f-31d0-4b33-a41c-3ec123ea3e6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
