<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cari Tahu Lebih Lanjut</name>
   <tag></tag>
   <elementGuidId>ea0ca052-3485-47e5-b86a-53532462ee8d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.title-cta > a.btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='ironc-pencegahan']/div/div[2]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d0a6f75-03f5-4941-b792-12a520405ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>produk/sgm-eksplor-3-plus</value>
      <webElementGuid>0f5bcb7d-863a-4f4d-a856-57ddaede6735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>ba98d896-63d3-4020-8e4c-342fa7b612dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cari Tahu Lebih Lanjut</value>
      <webElementGuid>409a09de-bbd4-4ce4-b858-86d5464f8e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ironc-pencegahan&quot;)/div[@class=&quot;content-container&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;cta-ironc-pencegahan&quot;]/div[@class=&quot;title-cta&quot;]/a[@class=&quot;btn&quot;]</value>
      <webElementGuid>0b313ffa-d49e-4311-9324-281581b9bd60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='ironc-pencegahan']/div/div[2]/div[2]/div/a</value>
      <webElementGuid>fa80b48f-7181-4334-8979-efc08cbc027c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cari Tahu Lebih Lanjut')]</value>
      <webElementGuid>15c92724-c85a-48e5-9855-b428ec49367a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anemia'])[4]/following::a[1]</value>
      <webElementGuid>0ddc60bb-e9c7-4bab-ae3b-cca3d76a1561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Kami'])[1]/preceding::a[1]</value>
      <webElementGuid>818498f5-8b9d-40c2-b563-1a38e8e225c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat &amp; Ketentuan'])[1]/preceding::a[2]</value>
      <webElementGuid>2a2a3a49-a450-4094-bbf5-53f07b197457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cari Tahu Lebih Lanjut']/parent::*</value>
      <webElementGuid>97dd92fa-9248-4643-9c9e-36e5612613d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'produk/sgm-eksplor-3-plus')]</value>
      <webElementGuid>32820959-79f7-44cc-8d6f-2bc27575dffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a</value>
      <webElementGuid>fabdde49-974c-4323-bea0-ebef6aab5ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'produk/sgm-eksplor-3-plus' and (text() = 'Cari Tahu Lebih Lanjut' or . = 'Cari Tahu Lebih Lanjut')]</value>
      <webElementGuid>8eb7f095-8611-45de-992c-d65704d2b448</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
