<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_prev artikel</name>
   <tag></tag>
   <elementGuidId>a0a41602-9225-49e4-b6e0-e61b30d14936</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.pagination > li > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paginationListArticle']/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fade2410-76cb-4e69-85e9-53f865f71407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>941d73b9-cf72-4155-b6ca-dfab791ed984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>«</value>
      <webElementGuid>75ef4388-f949-46eb-85f3-d511b3fc4284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paginationListArticle&quot;)/ul[@class=&quot;pagination&quot;]/li[1]/a[1]/span[1]</value>
      <webElementGuid>17bd2367-12f7-4949-bec5-d3c00deaaa19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paginationListArticle']/ul/li/a/span</value>
      <webElementGuid>e3c40fa7-054f-42f8-a2f8-f614b2e3f1cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baca Sekarang >'])[5]/following::span[1]</value>
      <webElementGuid>5e0094ce-e158-44a3-a828-3a6a05b4739c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kesehatan'])[3]/following::span[2]</value>
      <webElementGuid>8db8ef44-a5fa-44f2-acd0-35108cdbabe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anemia'])[4]/preceding::span[2]</value>
      <webElementGuid>1e71f42b-96ac-4e87-b500-700524c07cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='«']/parent::*</value>
      <webElementGuid>4f9acf3f-29ff-44bc-b2b2-e7b71483b25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/ul/li/a/span</value>
      <webElementGuid>637cab7c-a730-4115-bc5b-79bfcf50acb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '«' or . = '«')]</value>
      <webElementGuid>2f5b6c0a-cd63-4211-86f7-1e6e16bf82a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
