<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kondisi Bunda</name>
   <tag></tag>
   <elementGuidId>41e0aaca-c7c0-4fb0-89f5-5bfb302e97af</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kondisi-bunda</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kondisi-bunda']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'kondisi-bunda' and (text() = 'Kondisi Bunda' or . = 'Kondisi Bunda')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9592c4a8-64a9-4af0-8cff-68ae3ab62112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kondisi-bunda</value>
      <webElementGuid>9e58423a-c29f-4d5d-850d-39f113f73bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>de30ba93-1196-4949-b86b-16cdb75356b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kondisi Bunda</value>
      <webElementGuid>acf657d4-d8ca-4ecc-a6cc-2817374561e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kondisi-bunda&quot;)</value>
      <webElementGuid>ada30036-2516-4396-91ad-4de732b11aa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='kondisi-bunda']</value>
      <webElementGuid>f838d8a1-5e16-4c67-98f6-e79836653902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerkgm']/div/div[4]/div</value>
      <webElementGuid>95b27734-4373-4de1-a299-c46874811e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kondisi Bunda (Kehamilan dan Anak)'])[1]/following::div[1]</value>
      <webElementGuid>ff636a33-e81a-4f5e-824a-b0fa5a8b7cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password*'])[1]/following::div[3]</value>
      <webElementGuid>47f8a579-5ef3-47fd-b220-572143bb2e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sedang Hamil'])[1]/preceding::div[1]</value>
      <webElementGuid>e053a49a-7f35-44f3-9063-cf2814f7e3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sedang Hamil dan Memiliki Anak'])[1]/preceding::div[2]</value>
      <webElementGuid>ceda2d0a-7e3c-4e57-b390-50ef045fb82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kondisi Bunda']/parent::*</value>
      <webElementGuid>dfef4344-5c41-46bc-acae-66e986761c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div</value>
      <webElementGuid>b1fa7dba-9a68-4972-88f6-ee52eb2b5ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'kondisi-bunda' and (text() = 'Kondisi Bunda' or . = 'Kondisi Bunda')]</value>
      <webElementGuid>709c5e03-633e-442b-aac1-e9d7ee0636f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
