<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kondisi Bunda</name>
   <tag></tag>
   <elementGuidId>41e0aaca-c7c0-4fb0-89f5-5bfb302e97af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kondisi-bunda']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kondisi-bunda</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;kondisi-bunda&quot;)[count(. | //div[@id = 'kondisi-bunda' and @class = 'form-control' and (text() = 'Kondisi Bunda' or . = 'Kondisi Bunda')]) = count(//div[@id = 'kondisi-bunda' and @class = 'form-control' and (text() = 'Kondisi Bunda' or . = 'Kondisi Bunda')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a06f546c-f617-439a-8772-2b61914e97aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kondisi-bunda</value>
      <webElementGuid>9b266d6b-d535-4ff6-9fb4-07a4f402814e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fb971d4d-844a-48a6-a093-56c4ece1475b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kondisi Bunda</value>
      <webElementGuid>536e4c48-d91d-4015-8fa3-9c6f78003454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kondisi-bunda&quot;)</value>
      <webElementGuid>03e99ade-b39c-41ae-9e98-cd0cdfabfb26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='kondisi-bunda']</value>
      <webElementGuid>5794172c-fa86-4438-8e7c-101318b9d8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerkgm']/div/div[4]/div</value>
      <webElementGuid>9f372b5d-05d4-4026-8fb3-a5e4aa097daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kondisi Bunda (Kehamilan dan Anak)'])[1]/following::div[1]</value>
      <webElementGuid>1087b0c0-3da5-4746-b3cc-8522e4080472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password*'])[1]/following::div[3]</value>
      <webElementGuid>0fcf1af6-c328-4ab0-b663-d9114be0335b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sedang Hamil'])[1]/preceding::div[1]</value>
      <webElementGuid>58ecf417-0149-4091-bb09-7d0e26f607bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sedang Hamil dan Memiliki Anak'])[1]/preceding::div[2]</value>
      <webElementGuid>50d047d2-4eaf-4351-98e3-d69496ce6a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kondisi Bunda']/parent::*</value>
      <webElementGuid>9755c6d3-fda4-41f7-925f-d1c892448c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div</value>
      <webElementGuid>71b6fe5b-c68a-4d18-aa67-7807b2604825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'kondisi-bunda' and (text() = 'Kondisi Bunda' or . = 'Kondisi Bunda')]</value>
      <webElementGuid>5a512e0f-c7e2-4b64-9198-1aff93eadbaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
