<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cookie_register-new-kgm</name>
   <tag></tag>
   <elementGuidId>a1a95535-47e3-4fc7-85bc-5d1c45db1f23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register-new-kgm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='register-new-kgm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7f739c9-a627-44e0-8018-923e0648184a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>116b6bd2-63fa-4791-adc4-bd01e2e8e71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary text-center check</value>
      <webElementGuid>d9601e15-9abb-4804-9977-0863e8dc9444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register-new-kgm</value>
      <webElementGuid>16208401-a1c9-4556-82a9-8cc3b6c3d4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>eef83d73-854a-4128-9e5f-43de89b5666c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-new-kgm&quot;)</value>
      <webElementGuid>e19e4c3d-4f4b-4655-8e96-d5ceff0a41d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='register-new-kgm']</value>
      <webElementGuid>c1ac28a0-9712-41b4-b79b-d52eb174a541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerkgm']/div/div[11]/input</value>
      <webElementGuid>b7ee47aa-55a1-4e56-b339-8972e91f06ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>c6aec6bb-5072-4114-97db-5c1debda4fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'register-new-kgm']</value>
      <webElementGuid>6fa7da95-84c6-44f9-9f8f-4ca49794c519</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
