<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Lengkap_firstname</name>
   <tag></tag>
   <elementGuidId>66c3315a-25ec-4532-89b8-6fd4d0dc5de4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#namalengkap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namalengkap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d2b3193-1acb-472f-a56e-6554b3f075b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstname</value>
      <webElementGuid>fdff3f25-0d2a-4d50-a851-65b9aab1ccfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0de32ba6-cde7-4bac-a47f-2f1f89e53ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namalengkap</value>
      <webElementGuid>cb883484-99af-4084-83fe-13d47d37a6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>daf1af2b-792b-4a31-9403-ca64eaf8ca77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mohon Isikan Nama Lengkap Bunda</value>
      <webElementGuid>6f8faa39-4372-4f12-bdef-25765c80ac2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namalengkap&quot;)</value>
      <webElementGuid>c9344c8d-492e-4486-84f6-bb19773d62f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namalengkap']</value>
      <webElementGuid>2ad1b972-126a-40aa-895c-6a0949daa40c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerkgm']/div/div/input</value>
      <webElementGuid>820990c5-30ac-42ea-bc27-0ffe77b124f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[3]/form/div/div/input</value>
      <webElementGuid>99deb855-f5e8-4c9a-b754-1ef07c290b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'firstname' and @type = 'text' and @id = 'namalengkap' and @placeholder = 'Mohon Isikan Nama Lengkap Bunda']</value>
      <webElementGuid>adf31a71-93f8-4ff5-bd1e-b5fe5b528067</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
