<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Lahir Anak_dp1690640576143</name>
   <tag></tag>
   <elementGuidId>ae165a74-473d-41f5-9547-17213f1adb28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dp1690640576143</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dp1690640576143']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8e8c877-d76c-431e-8d23-29cddc275e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3a9058e-1589-4c51-a4c4-7de050910d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control reg-calendar must-field hasDatepicker</value>
      <webElementGuid>1bf6f081-678b-4a29-95f7-92e530ce1de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: 15-12-2019</value>
      <webElementGuid>45f750e5-5e70-49fe-b257-06f6230e93e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dp1690640576143</value>
      <webElementGuid>a0a1df66-ec81-495b-a7fe-2d8d9c47a449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dp1690640576143&quot;)</value>
      <webElementGuid>2a01d948-40ad-49c5-8491-8ac1642a6fba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dp1690640576143']</value>
      <webElementGuid>14cfef1a-5c47-4ead-b8b5-b8bfe894fc6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='child']/div/div/input</value>
      <webElementGuid>217527a4-43ed-4a4a-85b5-90a55e5a037e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>f0066a06-c53e-4f61-97a5-b1f71a54949f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Contoh: 15-12-2019' and @id = 'dp1690640576143']</value>
      <webElementGuid>55bee9cc-3de9-41ac-b089-803b88e4271a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
