<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Ponsel_msisdn</name>
   <tag></tag>
   <elementGuidId>6ebf3127-269e-439e-8932-b20374e749e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#handphone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='handphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60a055ee-6359-45d7-bad8-9f7226deb23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>msisdn</value>
      <webElementGuid>3efaecfc-3ca7-4c42-8fb1-f098ebf70f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>945e5762-0e82-4edd-938d-ef8fd6735cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>handphone</value>
      <webElementGuid>ea20abbf-879c-468c-8b90-f6228aaca9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6cc4e0b9-5c35-4ca0-a0b7-2301323d5d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mohon Isikan Nomor Ponsel Bunda</value>
      <webElementGuid>6bc0375f-ebeb-4805-9ede-22d51b83851a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;handphone&quot;)</value>
      <webElementGuid>e63d693a-30ef-48e4-a21a-e847097ed987</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='handphone']</value>
      <webElementGuid>8d77d809-a977-40d7-8e6c-fafac335cffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerkgm']/div/div[2]/input</value>
      <webElementGuid>64f14623-97ba-4025-ba16-57db5e7c4a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a5ea3648-9521-44ae-ac39-e14d241f7597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'msisdn' and @type = 'number' and @id = 'handphone' and @placeholder = 'Mohon Isikan Nomor Ponsel Bunda']</value>
      <webElementGuid>1bc4952d-df8a-43ed-90e5-52ee81585932</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
