<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cookie_checkmark</name>
   <tag></tag>
   <elementGuidId>d8499c5d-4c94-4732-a02e-cedc798ccfa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='registerkgm']/div/div[11]/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b00e0be2-5f34-4a9e-8a02-4f733f31dd7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>0d028a90-beaa-4f3f-b1e7-84cddfefcc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerkgm&quot;)/div[@class=&quot;register-form&quot;]/div[@class=&quot;check-submit&quot;]/div[@class=&quot;checkbox checkbox-register&quot;]/label[@class=&quot;font-thin&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>2ec584cd-8fcd-4083-88a3-7c2fb94146f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerkgm']/div/div[11]/div/label/span</value>
      <webElementGuid>81614e5f-2b0f-4c40-a92b-31b085a1bbe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>fa6c5eef-a285-4395-b07b-3d3d12edda72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
